###Day 17 — Objective

To train and evaluate a comparable object detection model on enhanced underwater images using White Balance and CLAHE,and compare its detection performance with the original-image baseline across all three supplied datasets.

In [ ]:
from google.colab import drive
import torch
drive.mount("/content/drive")
print("Google Drive mounted successfully!")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Google Drive mounted successfully!

In [ ]:
import os
import shutil
SOURCE="/content/drive/MyDrive/Dataset_V1_Enhanced"
DEST="/content/Dataset_V1_Enhanced"
if os.path.exists(DEST):
    shutil.rmtree(DEST)
shutil.copytree(SOURCE,DEST)
print("Enhanced dataset copied successfully!")
print("Source:",SOURCE)
print("Local path:",DEST)

Enhanced dataset copied successfully!
Source: /content/drive/MyDrive/Dataset_V1_Enhanced
Local path: /content/Dataset_V1_Enhanced

In [ ]:
import os
base="/content/Dataset_V1_Enhanced"
datasets=[
    "DIATAquarium.v4i.yolov8",
    "Aquatic Plant.v2i.yolov8",
    "well.v8i.yolov8"
]
for dataset in datasets:
    print("\n",dataset)
    path=os.path.join(base,dataset)
    for split in ["train","valid","test"]:
        images=os.path.join(path,split,"images")
        labels=os.path.join(path,split,"labels")
        print(split,
              "images:",os.path.exists(images),
              "labels:",os.path.exists(labels))

 DIATAquarium.v4i.yolov8
train images: True labels: True
valid images: True labels: True
test images: False labels: False

 Aquatic Plant.v2i.yolov8
train images: True labels: True
valid images: False labels: False
test images: False labels: False

 well.v8i.yolov8
train images: True labels: True
valid images: False labels: False
test images: False labels: False

In [ ]:
import os
for dataset in [
    "DIATAquarium.v4i.yolov8",
    "Aquatic Plant.v2i.yolov8",
    "well.v8i.yolov8"
]:
    print("\n"+dataset)
    path=f"/content/Dataset_V1/{dataset}"
    for split in ["train","valid","test"]:
        split_path=os.path.join(path,split)
        print(split,os.path.exists(split_path))

DIATAquarium.v4i.yolov8
train False
valid False
test False

Aquatic Plant.v2i.yolov8
train False
valid False
test False

well.v8i.yolov8
train False
valid False
test False

In [ ]:
import os
print("Folders inside /content:")
for item in os.listdir("/content"):
    if os.path.isdir(os.path.join("/content",item)):
        print(item)

Folders inside /content:
.config
drive
Dataset_V1_Enhanced
sample_data

In [ ]:
import os
original="/content/drive/MyDrive/Dataset_V1"
print("Dataset_V1 exists:",os.path.exists(original))
if os.path.exists(original):
    print("\nDatasets found:")
    for item in os.listdir(original):
        if os.path.isdir(os.path.join(original,item)):
            print(item)

Dataset_V1 exists: True

Datasets found:
Aquatic Plant.v2i.yolov8
well.v8i.yolov8
split_plan
DIATAquarium.v4i.yolov8

In [ ]:
import os
base="/content/drive/MyDrive/Dataset_V1"
datasets=[
    "DIATAquarium.v4i.yolov8",
    "Aquatic Plant.v2i.yolov8",
    "well.v8i.yolov8"
]
for dataset in datasets:
    print("\n"+dataset)
    path=os.path.join(base,dataset)
    for split in ["train","valid","test"]:
        images=os.path.join(path,split,"images")
        labels=os.path.join(path,split,"labels")
        print(
            split,
            "images:",os.path.exists(images),
            "labels:",os.path.exists(labels)
        )

DIATAquarium.v4i.yolov8
train images: True labels: True
valid images: True labels: True
test images: False labels: False

Aquatic Plant.v2i.yolov8
train images: True labels: True
valid images: True labels: True
test images: True labels: True

well.v8i.yolov8
train images: True labels: True
valid images: True labels: True
test images: True labels: True

In [ ]:
import os
import cv2
import numpy as np
from tqdm import tqdm
ORIGINAL="/content/drive/MyDrive/Dataset_V1"
ENHANCED="/content/Dataset_V1_Enhanced"
def white_balance(img):
    lab=cv2.cvtColor(img,cv2.COLOR_BGR2LAB)
    l,a,b=cv2.split(lab)
    avg_a=np.mean(a)
    avg_b=np.mean(b)
    a=np.clip(a-(avg_a-128)*l/255,0,255).astype(np.uint8)
    b=np.clip(b-(avg_b-128)*l/255,0,255).astype(np.uint8)
    lab=cv2.merge((l,a,b))
    return cv2.cvtColor(lab,cv2.COLOR_LAB2BGR)
def apply_clahe(img):
    lab=cv2.cvtColor(img,cv2.COLOR_BGR2LAB)
    l,a,b=cv2.split(lab)
    clahe=cv2.createCLAHE(clipLimit=2.0,tileGridSize=(8,8))
    l=clahe.apply(l)
    enhanced=cv2.merge((l,a,b))
    return cv2.cvtColor(enhanced,cv2.COLOR_LAB2BGR)
def enhance_image(img):
    img=white_balance(img)
    img=apply_clahe(img)
    return img
datasets=[
    "DIATAquarium.v4i.yolov8",
    "Aquatic Plant.v2i.yolov8",
    "well.v8i.yolov8"
]
for dataset in datasets:
    print("\nProcessing:",dataset)
    for split in ["valid","test"]:
        src_images=os.path.join(ORIGINAL,dataset,split,"images")
        src_labels=os.path.join(ORIGINAL,dataset,split,"labels")
        if not os.path.exists(src_images):
            print(split,": not available")
            continue
        dst_images=os.path.join(ENHANCED,dataset,split,"images")
        dst_labels=os.path.join(ENHANCED,dataset,split,"labels")
        os.makedirs(dst_images,exist_ok=True)
        os.makedirs(dst_labels,exist_ok=True)
        image_files=[
            f for f in os.listdir(src_images)
            if f.lower().endswith((".jpg",".jpeg",".png",".bmp"))
        ]

        for filename in tqdm(image_files,desc=split):
            src=os.path.join(src_images,filename)
            dst=os.path.join(dst_images,filename)
            img=cv2.imread(src)
            if img is None:
                print("Could not read:",filename)
                continue
            enhanced=enhance_image(img)
            cv2.imwrite(dst,enhanced)
        label_files=[
            f for f in os.listdir(src_labels)
            if f.lower().endswith(".txt")
        ]
        for filename in label_files:
            src=os.path.join(src_labels,filename)
            dst=os.path.join(dst_labels,filename)
            if not os.path.exists(dst):
                import shutil
                shutil.copy2(src,dst)
        print(split,"completed:",len(image_files),"images")

Processing: DIATAquarium.v4i.yolov8

valid: 100%|██████████| 773/773 [02:40<00:00,  4.82it/s]

valid completed: 773 images
test : not available

Processing: Aquatic Plant.v2i.yolov8

valid: 100%|██████████| 179/179 [00:08<00:00, 22.26it/s]

valid completed: 179 images

test: 100%|██████████| 89/89 [01:07<00:00,  1.33it/s]

test completed: 89 images

Processing: well.v8i.yolov8

valid: 100%|██████████| 191/191 [00:09<00:00, 20.99it/s]

valid completed: 191 images

test: 100%|██████████| 184/184 [00:10<00:00, 17.76it/s]

test completed: 184 images

In [ ]:
import os
base="/content/Dataset_V1_Enhanced"
datasets=[
    "DIATAquarium.v4i.yolov8",
    "Aquatic Plant.v2i.yolov8",
    "well.v8i.yolov8"
]
for dataset in datasets:
    print("\n"+dataset)
    dataset_path=os.path.join(base,dataset)
    for split in ["train","valid","test"]:
        images_path=os.path.join(dataset_path,split,"images")
        labels_path=os.path.join(dataset_path,split,"labels")
        if not os.path.exists(images_path):
            print(split,": not available")
            continue
        images=[
            f for f in os.listdir(images_path)
            if f.lower().endswith((".jpg",".jpeg",".png",".bmp"))
        ]
        labels=[
            f for f in os.listdir(labels_path)
            if f.lower().endswith(".txt")
        ]
        image_names={os.path.splitext(f)[0] for f in images}
        label_names={os.path.splitext(f)[0] for f in labels}
        missing_labels=image_names-label_names
        extra_labels=label_names-image_names
        print(
            split,
            "| images:",len(images),
            "| labels:",len(labels),
            "| missing labels:",len(missing_labels),
            "| extra labels:",len(extra_labels)
        )

DIATAquarium.v4i.yolov8
train | images: 1410 | labels: 1462 | missing labels: 1156 | extra labels: 1208
valid | images: 773 | labels: 773 | missing labels: 0 | extra labels: 0
test : not available

Aquatic Plant.v2i.yolov8
train | images: 1867 | labels: 1876 | missing labels: 16 | extra labels: 25
valid | images: 179 | labels: 179 | missing labels: 0 | extra labels: 0
test | images: 89 | labels: 89 | missing labels: 0 | extra labels: 0

well.v8i.yolov8
train | images: 3782 | labels: 3768 | missing labels: 27 | extra labels: 13
valid | images: 191 | labels: 191 | missing labels: 0 | extra labels: 0
test | images: 184 | labels: 184 | missing labels: 0 | extra labels: 0

In [ ]:
import os
base="/content/Dataset_V1_Enhanced"
configs={
    "DIATAquarium.v4i.yolov8":{
        "nc":11,
        "names":[
            "Aquatic Plant",
            "Camera",
            "Conch-Shell",
            "Fish",
            "Fishes",
            "Pluco",
            "Shark",
            "Temperature Sensor",
            "Water-Pump",
            "Water-filter",
            "betta"
        ]
    },
    "Aquatic Plant.v2i.yolov8":{
        "nc":1,
        "names":["Aquatic_plant"]
    },
    "well.v8i.yolov8":{
        "nc":4,
        "names":[
            "Inlet-pipe",
            "fishes",
            "school-of-fish",
            "stone"
        ]
    }
}
for dataset,config in configs.items():
    yaml_path=os.path.join(base,dataset,"enhanced.yaml")
    lines=[
        f"path: {os.path.join(base,dataset)}",
        "train: train/images",
        "val: valid/images"
    ]
    if os.path.exists(os.path.join(base,dataset,"test","images")):
        lines.append("test: test/images")
    lines.append(f"nc: {config['nc']}")
    lines.append("names:")
    for i,name in enumerate(config["names"]):
        lines.append(f"  {i}: {name}")
    with open(yaml_path,"w") as f:
        f.write("\n".join(lines)+"\n")
    print("Created:",yaml_path)

Created: /content/Dataset_V1_Enhanced/DIATAquarium.v4i.yolov8/enhanced.yaml
Created: /content/Dataset_V1_Enhanced/Aquatic Plant.v2i.yolov8/enhanced.yaml
Created: /content/Dataset_V1_Enhanced/well.v8i.yolov8/enhanced.yaml

In [ ]:
import os
base="/content/Dataset_V1_Enhanced"
datasets=[
"DIATAquarium.v4i.yolov8",
"Aquatic Plant.v2i.yolov8",
"well.v8i.yolov8"
]

for dataset in datasets:
    yaml_path=os.path.join(base,dataset,"enhanced.yaml")
    print("\n"+dataset)
    print("-"*40)
    with open(yaml_path,"r") as f:
        print(f.read())

DIATAquarium.v4i.yolov8
----------------------------------------
path: /content/Dataset_V1_Enhanced/DIATAquarium.v4i.yolov8
train: train/images
val: valid/images
nc: 11
names:
  0: Aquatic Plant
  1: Camera
  2: Conch-Shell
  3: Fish
  4: Fishes
  5: Pluco
  6: Shark
  7: Temperature Sensor
  8: Water-Pump
  9: Water-filter
  10: betta


Aquatic Plant.v2i.yolov8
----------------------------------------
path: /content/Dataset_V1_Enhanced/Aquatic Plant.v2i.yolov8
train: train/images
val: valid/images
test: test/images
nc: 1
names:
  0: Aquatic_plant


well.v8i.yolov8
----------------------------------------
path: /content/Dataset_V1_Enhanced/well.v8i.yolov8
train: train/images
val: valid/images
test: test/images
nc: 4
names:
  0: Inlet-pipe
  1: fishes
  2: school-of-fish
  3: stone

In [ ]:
!pip install ultralytics

Collecting ultralytics
  Downloading ultralytics-8.4.155-py3-none-any.whl.metadata (46 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.5/46.5 kB 3.9 MB/s eta 0:00:00
Requirement already satisfied: cloudpickle>=3.1.1 in /usr/local/lib/python3.13/dist-packages (from ultralytics) (3.1.2)
Requirement already satisfied: filelock>=3.16.1 in /usr/local/lib/python3.13/dist-packages (from ultralytics) (3.32.5)
Requirement already satisfied: numpy>=1.23.0 in /usr/local/lib/python3.13/dist-packages (from ultralytics) (2.1.3)
Requirement already satisfied: matplotlib>=3.3.0 in /usr/local/lib/python3.13/dist-packages (from ultralytics) (3.10.0)
Requirement already satisfied: opencv-python!=4.13.0.90,>=4.7.0 in /usr/local/lib/python3.13/dist-packages (from ultralytics) (5.0.0.93)
Requirement already satisfied: pillow>=7.1.2 in /usr/local/lib/python3.13/dist-packages (from ultralytics) (11.3.0)
Requirement already satisfied: pyyaml>=5.3.1 in /usr/local/lib/python3.13/dist-packages (from ultralytics) (6.0.3)
Requirement already satisfied: requests>=2.23.0 in /usr/local/lib/python3.13/dist-packages (from ultralytics) (2.32.4)
Requirement already satisfied: torch>=1.8.0 in /usr/local/lib/python3.13/dist-packages (from ultralytics) (2.11.0+cu128)
Requirement already satisfied: torchvision>=0.9.0 in /usr/local/lib/python3.13/dist-packages (from ultralytics) (0.26.0+cu128)
Requirement already satisfied: psutil>=5.8.0 in /usr/local/lib/python3.13/dist-packages (from ultralytics) (5.9.5)
Requirement already satisfied: polars>=0.20.0 in /usr/local/lib/python3.13/dist-packages (from ultralytics) (1.35.2)
Requirement already satisfied: nvidia-ml-py>=12.0.0 in /usr/local/lib/python3.13/dist-packages (from ultralytics) (13.610.43)
Collecting ultralytics-thop>=2.1.6 (from ultralytics)
  Downloading ultralytics_thop-2.1.6-py3-none-any.whl.metadata (13 kB)
Collecting ultralytics-platform>=0.1.45 (from ultralytics)
  Downloading ultralytics_platform-0.1.48-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.3.0->ultralytics) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.3.0->ultralytics) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.3.0->ultralytics) (4.64.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.3.0->ultralytics) (1.5.1)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.3.0->ultralytics) (26.3)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.3.0->ultralytics) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.3.0->ultralytics) (2.9.0.post0)
Requirement already satisfied: polars-runtime-32==1.35.2 in /usr/local/lib/python3.13/dist-packages (from polars>=0.20.0->ultralytics) (1.35.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests>=2.23.0->ultralytics) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests>=2.23.0->ultralytics) (3.19)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests>=2.23.0->ultralytics) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests>=2.23.0->ultralytics) (2026.7.22)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.13/dist-packages (from torch>=1.8.0->ultralytics) (4.16.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.13/dist-packages (from torch>=1.8.0->ultralytics) (80.10.2)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.13/dist-packages (from torch>=1.8.0->ultralytics) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.13/dist-packages (from torch>=1.8.0->ultralytics) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.13/dist-packages (from torch>=1.8.0->ultralytics) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.13/dist-packages (from torch>=1.8.0->ultralytics) (2025.12.0)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.8.0->ultralytics) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.13/dist-packages (from torch>=1.8.0->ultralytics) (12.9.7)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.13/dist-packages (from torch>=1.8.0->ultralytics) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.13/dist-packages (from torch>=1.8.0->ultralytics) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.13/dist-packages (from torch>=1.8.0->ultralytics) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.13/dist-packages (from torch>=1.8.0->ultralytics) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.13/dist-packages (from torch>=1.8.0->ultralytics) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.8.0->ultralytics) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.8.0->ultralytics) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.8.0->ultralytics) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.8.0->ultralytics) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.8.0->ultralytics) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.8.0->ultralytics) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.8.0->ultralytics) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.8.0->ultralytics) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.8.0->ultralytics) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.8.0->ultralytics) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.8.0->ultralytics) (12.8.90)
Requirement already satisfied: httpx<1,>=0.28 in /usr/local/lib/python3.13/dist-packages (from ultralytics-platform>=0.1.45->ultralytics) (0.28.1)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.13/dist-packages (from cuda-bindings<13,>=12.9.4->torch>=1.8.0->ultralytics) (1.8.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.28->ultralytics-platform>=0.1.45->ultralytics) (4.14.2)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.28->ultralytics-platform>=0.1.45->ultralytics) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.13/dist-packages (from httpcore==1.*->httpx<1,>=0.28->ultralytics-platform>=0.1.45->ultralytics) (0.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.7->matplotlib>=3.3.0->ultralytics) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from sympy>=1.13.3->torch>=1.8.0->ultralytics) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2->torch>=1.8.0->ultralytics) (3.0.3)
Downloading ultralytics-8.4.155-py3-none-any.whl (1.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 34.9 MB/s eta 0:00:00
Downloading ultralytics_platform-0.1.48-py3-none-any.whl (78 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.4/78.4 kB 5.1 MB/s eta 0:00:00
Downloading ultralytics_thop-2.1.6-py3-none-any.whl (30 kB)
Installing collected packages: ultralytics-platform, ultralytics-thop, ultralytics
Successfully installed ultralytics-8.4.155 ultralytics-platform-0.1.48 ultralytics-thop-2.1.6

In [ ]:
from ultralytics import YOLO
DIAT_YAML="/content/Dataset_V1_Enhanced/DIATAquarium.v4i.yolov8/enhanced.yaml"
model=YOLO("yolov8n.pt")
results=model.train(
data=DIAT_YAML,
epochs=30,
imgsz=640,
batch=16,
device=0,
project="/content/Day17_YOLO_Enhanced",
name="DIATAquarium"
)

Creating new Ultralytics Settings v0.0.8 file ✅
View Ultralytics Settings with 'yolo settings' or at '/root/.config/Ultralytics/settings.json'
Update Settings with 'yolo settings key=value', i.e. 'yolo settings runs_dir=path/to/dir'. For help see https://docs.ultralytics.com/usage/settings.
Downloading https://github.com/ultralytics/assets/releases/download/v8.4.0/yolov8n.pt to 'yolov8n.pt': 100% ━━━━━━━━━━━━ 6.2MB 216.2MB/s 0.0s
Ultralytics 8.4.155 🚀 Python-3.13.15 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=16, bgr=0.0, box=7.5, cache=False, cfg=None, channels_last=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, cls_remap=True, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/content/Dataset_V1_Enhanced/DIATAquarium.v4i.yolov8/enhanced.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dgrad=0.5, dis=6.0, distill_model=None, dlam=1.0, dlog=1.0, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=30, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8n.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=DIATAquarium, nbs=64, nms=None, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=/content/Day17_YOLO_Enhanced, quantize=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/content/Day17_YOLO_Enhanced/DIATAquarium, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=tracktrack.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Downloading https://ultralytics.com/assets/Arial.ttf to '/root/.config/Ultralytics/Arial.ttf': 100% ━━━━━━━━━━━━ 755.1KB 94.1MB/s 0.0s
Overriding model.yaml nc=80 with nc=11

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 22        [15, 18, 21]  1    753457  ultralytics.nn.modules.head.Detect           [11, 16, None, [64, 128, 256]]
Model summary: 129 layers, 3,012,993 parameters, 3,012,977 gradients, 8.2 GFLOPs

Transferred 319/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: downloading yolo26n.pt for AMP checks (one-time, not used for training)...
Downloading https://github.com/ultralytics/assets/releases/download/v8.4.0/yolo26n.pt to 'weights/yolo26n.pt': 100% ━━━━━━━━━━━━ 5.3MB 256.4MB/s 0.0s
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 2477.7±1592.6 MB/s, size: 517.4 KB)
train: Scanning /content/Dataset_V1_Enhanced/DIATAquarium.v4i.yolov8/train/labels... 254 images, 1177 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1410/1410 1.1Kit/s 1.3s
train: New cache created: /content/Dataset_V1_Enhanced/DIATAquarium.v4i.yolov8/train/labels.cache
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 1111.8±1005.9 MB/s, size: 474.8 KB)
val: Scanning /content/Dataset_V1_Enhanced/DIATAquarium.v4i.yolov8/valid/labels... 773 images, 59 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 773/773 1.4Kit/s 0.6s
val: New cache created: /content/Dataset_V1_Enhanced/DIATAquarium.v4i.yolov8/valid/labels.cache
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.000667, momentum=0.9) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Plotting labels to /content/Day17_YOLO_Enhanced/DIATAquarium/labels.jpg...
Using 1410 train, 773 val images for fraction=1.0 at imgsz=640
Using 2 dataloader workers
Logging results to /content/Day17_YOLO_Enhanced/DIATAquarium
Starting training for 30 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/30      2.08G      1.364      7.595       1.45          1        640: 100% ━━━━━━━━━━━━ 89/89 2.3it/s 39.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 25/25 1.8it/s 14.2s
                   all        773       1504    0.00587      0.667      0.201     0.0996

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/30      2.38G      1.386      5.759      1.441          2        640: 100% ━━━━━━━━━━━━ 89/89 2.6it/s 34.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 25/25 1.9it/s 13.4s
                   all        773       1504       0.66      0.251      0.252      0.131

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/30      2.38G      1.367      5.186      1.435          0        640: 100% ━━━━━━━━━━━━ 89/89 2.7it/s 33.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 25/25 1.9it/s 13.5s
                   all        773       1504      0.769      0.157       0.24      0.125

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/30      2.38G      1.407       6.37      1.448          2        640: 100% ━━━━━━━━━━━━ 89/89 2.7it/s 33.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 25/25 1.9it/s 13.1s
                   all        773       1504      0.724      0.188      0.238       0.12

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/30      2.38G      1.426      4.531      1.416          1        640: 100% ━━━━━━━━━━━━ 89/89 2.7it/s 33.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 25/25 1.9it/s 13.3s
                   all        773       1504      0.718      0.264       0.28      0.147

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/30      2.38G      1.384      4.049      1.407          0        640: 100% ━━━━━━━━━━━━ 89/89 2.7it/s 32.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 25/25 1.9it/s 13.5s
                   all        773       1504      0.876       0.16      0.359      0.189

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/30      2.38G      1.389      4.226      1.411          1        640: 100% ━━━━━━━━━━━━ 89/89 2.7it/s 32.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 25/25 1.9it/s 13.4s
                   all        773       1504      0.516      0.307      0.332      0.179

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/30      2.38G      1.283      3.917      1.338          4        640: 100% ━━━━━━━━━━━━ 89/89 2.6it/s 34.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 25/25 2.0it/s 12.4s
                   all        773       1504      0.715      0.274      0.384      0.215

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/30      2.38G      1.277      3.355      1.344          2        640: 100% ━━━━━━━━━━━━ 89/89 2.6it/s 34.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 25/25 1.9it/s 13.5s
                   all        773       1504      0.751      0.213      0.373      0.188

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/30      2.38G      1.228      3.327      1.295          0        640: 100% ━━━━━━━━━━━━ 89/89 2.6it/s 33.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 25/25 1.9it/s 12.9s
                   all        773       1504      0.796      0.249      0.459      0.266

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/30      2.38G       1.28      3.162       1.34          1        640: 100% ━━━━━━━━━━━━ 89/89 2.7it/s 33.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 25/25 1.9it/s 13.1s
                   all        773       1504        0.7       0.26      0.442       0.24

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/30      2.38G      1.195      2.809      1.272          2        640: 100% ━━━━━━━━━━━━ 89/89 2.7it/s 33.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 25/25 1.9it/s 13.1s
                   all        773       1504      0.796      0.303      0.436      0.242

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/30      2.38G       1.16      2.974      1.263          0        640: 100% ━━━━━━━━━━━━ 89/89 2.7it/s 33.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 25/25 1.8it/s 13.7s
                   all        773       1504      0.831       0.35      0.456       0.25

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/30      2.38G      1.124      3.164      1.232          0        640: 100% ━━━━━━━━━━━━ 89/89 2.6it/s 33.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 25/25 1.9it/s 12.9s
                   all        773       1504      0.788       0.31      0.439      0.247

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/30      2.38G       1.11      2.762      1.212          0        640: 100% ━━━━━━━━━━━━ 89/89 2.5it/s 35.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 25/25 1.9it/s 13.0s
                   all        773       1504      0.759      0.437      0.548      0.328

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/30      2.38G      1.083      2.613        1.2          1        640: 100% ━━━━━━━━━━━━ 89/89 2.7it/s 33.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 25/25 1.8it/s 13.7s
                   all        773       1504       0.78      0.469      0.547      0.317

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/30      2.38G       1.09      2.581      1.208          0        640: 100% ━━━━━━━━━━━━ 89/89 2.6it/s 33.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 25/25 1.9it/s 13.3s
                   all        773       1504      0.886      0.364      0.517      0.299

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/30      2.38G      1.041      2.304      1.176          2        640: 100% ━━━━━━━━━━━━ 89/89 2.7it/s 33.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 25/25 1.9it/s 13.3s
                   all        773       1504      0.856      0.459       0.56      0.318

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/30      2.38G      1.034      2.518      1.167          1        640: 100% ━━━━━━━━━━━━ 89/89 2.7it/s 32.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 25/25 1.8it/s 13.7s
                   all        773       1504       0.86      0.495      0.565      0.328

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/30      2.38G     0.9901      3.104      1.145          0        640: 100% ━━━━━━━━━━━━ 89/89 2.6it/s 34.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 25/25 2.0it/s 12.3s
                   all        773       1504        0.9      0.419      0.578       0.34
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/30      2.38G     0.8711       3.85      1.066          0        640: 100% ━━━━━━━━━━━━ 89/89 2.5it/s 35.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 25/25 2.0it/s 12.3s
                   all        773       1504      0.262      0.602      0.483      0.294

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/30      2.38G     0.8747      3.005      1.054          0        640: 100% ━━━━━━━━━━━━ 89/89 3.0it/s 29.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 25/25 2.0it/s 12.2s
                   all        773       1504       0.89      0.369      0.544      0.313

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/30      2.38G     0.8694      3.152      1.097          2        640: 100% ━━━━━━━━━━━━ 89/89 3.0it/s 29.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 25/25 1.9it/s 13.0s
                   all        773       1504      0.235      0.659      0.497      0.291

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/30      2.38G      0.799      3.026      1.035          0        640: 100% ━━━━━━━━━━━━ 89/89 2.9it/s 30.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 25/25 1.9it/s 13.4s
                   all        773       1504      0.809      0.473      0.583      0.346

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/30      2.38G     0.8658       2.69      1.067          0        640: 100% ━━━━━━━━━━━━ 89/89 2.9it/s 30.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 25/25 1.9it/s 12.9s
                   all        773       1504       0.92      0.384      0.575      0.336

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/30      2.38G     0.8278      2.588      1.095          2        640: 100% ━━━━━━━━━━━━ 89/89 2.9it/s 30.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 25/25 2.0it/s 12.7s
                   all        773       1504      0.923      0.385      0.589      0.347

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/30      2.38G     0.7133      2.884      0.971          3        640: 100% ━━━━━━━━━━━━ 89/89 2.9it/s 30.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 25/25 1.9it/s 12.8s
                   all        773       1504      0.838      0.504      0.571      0.337

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/30      2.38G     0.7558      2.607     0.9952          0        640: 100% ━━━━━━━━━━━━ 89/89 2.9it/s 30.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 25/25 1.9it/s 13.0s
                   all        773       1504      0.904      0.417      0.586       0.35

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      29/30      2.38G     0.7549      2.351      1.027          2        640: 100% ━━━━━━━━━━━━ 89/89 2.9it/s 30.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 25/25 1.9it/s 13.4s
                   all        773       1504      0.912      0.394      0.588      0.357

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      30/30      2.38G     0.7249      2.733     0.9715          0        640: 100% ━━━━━━━━━━━━ 89/89 2.9it/s 30.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 25/25 1.9it/s 12.9s
                   all        773       1504      0.905      0.391      0.588      0.356

30 epochs completed in 0.392 hours.
Optimizer stripped from /content/Day17_YOLO_Enhanced/DIATAquarium/weights/last.pt, 6.2MB
Optimizer stripped from /content/Day17_YOLO_Enhanced/DIATAquarium/weights/best.pt, 6.2MB

Validating /content/Day17_YOLO_Enhanced/DIATAquarium/weights/best.pt...
Ultralytics 8.4.155 🚀 Python-3.13.15 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
Model summary (fused): 72 layers, 3,007,793 parameters, 0 gradients, 8.1 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 25/25 1.8it/s 13.6s

In [ ]:
import os

print(os.listdir("/content/drive/MyDrive"))

['Colab Notebooks', 'KDP-SCS645237-C.NITISH KUMAR-TEL.pdf', 'Classroom', 'Letter.gdoc', 'Dataset_V1_Enhanced (1)', 'Dataset_V1_Enhanced', 'Dataset_V1']

In [ ]:
import os
base="/content/drive/MyDrive/Dataset_V1/DIATAquarium.v4i.yolov8/train"
images=len([f for f in os.listdir(os.path.join(base,"images")) if f.lower().endswith((".jpg",".jpeg",".png",".bmp"))])
labels=len([f for f in os.listdir(os.path.join(base,"labels")) if f.lower().endswith(".txt")])
print("Original DIAT train images:",images)
print("Original DIAT train labels:",labels)

Original DIAT train images: 8121
Original DIAT train labels: 8121

In [ ]:
import os

for folder in ["Dataset_V1_Enhanced","Dataset_V1_Enhanced (1)"]:
    base=f"/content/drive/MyDrive/{folder}/DIATAquarium.v4i.yolov8/train/images"
    if os.path.exists(base):
        count=len([f for f in os.listdir(base) if f.lower().endswith((".jpg",".jpeg",".png",".bmp"))])
        print(folder,":",count,"images")
    else:
        print(folder,": DIAT folder not found")

Dataset_V1_Enhanced : 8121 images
Dataset_V1_Enhanced (1) : 8121 images

In [ ]:
import os

base="/content/drive/MyDrive/Dataset_V1_Enhanced/DIATAquarium.v4i.yolov8"

print(os.listdir(base))

['train', 'data.yaml']

In [ ]:
import os
import cv2
import shutil
from tqdm import tqdm
import numpy as np

ORIGINAL="/content/drive/MyDrive/Dataset_V1/DIATAquarium.v4i.yolov8"
ENHANCED="/content/drive/MyDrive/Dataset_V1_Enhanced/DIATAquarium.v4i.yolov8"

src_images=os.path.join(ORIGINAL,"valid","images")
src_labels=os.path.join(ORIGINAL,"valid","labels")

dst_images=os.path.join(ENHANCED,"valid","images")
dst_labels=os.path.join(ENHANCED,"valid","labels")

os.makedirs(dst_images,exist_ok=True)
os.makedirs(dst_labels,exist_ok=True)

def white_balance(img):
    lab=cv2.cvtColor(img,cv2.COLOR_BGR2LAB)
    l,a,b=cv2.split(lab)
    avg_a=np.mean(a)
    avg_b=np.mean(b)
    a=np.clip(a-(avg_a-128)*l/255,0,255).astype(np.uint8)
    b=np.clip(b-(avg_b-128)*l/255,0,255).astype(np.uint8)
    lab=cv2.merge((l,a,b))
    return cv2.cvtColor(lab,cv2.COLOR_LAB2BGR)

def apply_clahe(img):
    lab=cv2.cvtColor(img,cv2.COLOR_BGR2LAB)
    l,a,b=cv2.split(lab)
    clahe=cv2.createCLAHE(clipLimit=2.0,tileGridSize=(8,8))
    l=clahe.apply(l)
    enhanced=cv2.merge((l,a,b))
    return cv2.cvtColor(enhanced,cv2.COLOR_LAB2BGR)

def enhance_image(img):
    img=white_balance(img)
    img=apply_clahe(img)
    return img

image_files=[f for f in os.listdir(src_images) if f.lower().endswith((".jpg",".jpeg",".png",".bmp"))]

print("Validation images:",len(image_files))

for filename in tqdm(image_files,desc="Enhancing DIAT validation"):
    src=os.path.join(src_images,filename)
    dst=os.path.join(dst_images,filename)

    img=cv2.imread(src)

    if img is None:
        print("Could not read:",filename)
        continue

    enhanced=enhance_image(img)
    cv2.imwrite(dst,enhanced)

label_files=[f for f in os.listdir(src_labels) if f.lower().endswith(".txt")]

for filename in tqdm(label_files,desc="Copying validation labels"):
    shutil.copy2(
        os.path.join(src_labels,filename),
        os.path.join(dst_labels,filename)
    )

print("DIAT enhanced validation set completed.")
print("Images:",len(os.listdir(dst_images)))
print("Labels:",len(os.listdir(dst_labels)))

Validation images: 773

Enhancing DIAT validation: 100%|██████████| 773/773 [02:36<00:00,  4.95it/s]
Copying validation labels: 100%|██████████| 773/773 [00:14<00:00, 53.15it/s]

DIAT enhanced validation set completed.
Images: 773
Labels: 773

In [ ]:
yaml_path="/content/drive/MyDrive/Dataset_V1_Enhanced/DIATAquarium.v4i.yolov8/enhanced.yaml"
yaml_content="""path: /content/drive/MyDrive/Dataset_V1_Enhanced/DIATAquarium.v4i.yolov8
train: train/images
val: valid/images
nc: 11
names:
  0: Aquatic Plant
  1: Camera
  2: Conch-Shell
  3: Fish
  4: Fishes
  5: Pluco
  6: Shark
  7: Temperature Sensor
  8: Water-Pump
  9: Water-filter
  10: betta
"""

with open(yaml_path,"w") as f:
    f.write(yaml_content)

print("Enhanced YAML created:")
print(yaml_path)

Enhanced YAML created:
/content/drive/MyDrive/Dataset_V1_Enhanced/DIATAquarium.v4i.yolov8/enhanced.yaml

In [ ]:
import os

base="/content/drive/MyDrive/Dataset_V1_Enhanced/DIATAquarium.v4i.yolov8"

for split in ["train","valid"]:
    image_dir=os.path.join(base,split,"images")
    label_dir=os.path.join(base,split,"labels")

    images=len([f for f in os.listdir(image_dir) if f.lower().endswith((".jpg",".jpeg",".png",".bmp"))])
    labels=len([f for f in os.listdir(label_dir) if f.lower().endswith(".txt")])

    print(split,"images:",images,"labels:",labels)

print("\nYAML:")
with open(os.path.join(base,"enhanced.yaml")) as f:
    print(f.read())

train images: 8121 labels: 8121
valid images: 773 labels: 773

YAML:
path: /content/drive/MyDrive/Dataset_V1_Enhanced/DIATAquarium.v4i.yolov8
train: train/images
val: valid/images
nc: 11
names:
  0: Aquatic Plant
  1: Camera
  2: Conch-Shell
  3: Fish
  4: Fishes
  5: Pluco
  6: Shark
  7: Temperature Sensor
  8: Water-Pump
  9: Water-filter
  10: betta

In [ ]:
import shutil
import os

local="/content/Dataset_V1_Enhanced/DIATAquarium.v4i.yolov8"

if os.path.exists(local):
    shutil.rmtree(local)

print("Incomplete local DIAT enhanced folder removed.")

Incomplete local DIAT enhanced folder removed.

In [ ]:
import os
import shutil

source="/content/drive/MyDrive/Dataset_V1_Enhanced/DIATAquarium.v4i.yolov8"
destination="/content/Dataset_V1_Enhanced/DIATAquarium.v4i.yolov8"

print("Copying complete DIAT enhanced dataset...")
shutil.copytree(source,destination)
print("Copy completed.")

Copying complete DIAT enhanced dataset...
Copy completed.

In [ ]:
import os
base="/content/Dataset_V1_Enhanced/DIATAquarium.v4i.yolov8"
for split in ["train","valid"]:
    image_dir=os.path.join(base,split,"images")
    label_dir=os.path.join(base,split,"labels")

    images=len([f for f in os.listdir(image_dir) if f.lower().endswith((".jpg",".jpeg",".png",".bmp"))])
    labels=len([f for f in os.listdir(label_dir) if f.lower().endswith(".txt")])

    print(split,"images:",images,"labels:",labels)

train images: 8121 labels: 8121
valid images: 773 labels: 773

In [ ]:
from ultralytics import YOLO
DIAT_ENHANCED_YAML="/content/Dataset_V1_Enhanced/DIATAquarium.v4i.yolov8/enhanced.yaml"
model=YOLO("yolov8n.pt")
results=model.train(
    data=DIAT_ENHANCED_YAML,
    epochs=20,
    imgsz=640,
    batch=16,
    device=0,
    project="/content/drive/MyDrive/Day17_YOLO_Enhanced",
    name="DIATAquarium",
    exist_ok=True
)

Ultralytics 8.4.155 🚀 Python-3.13.15 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=16, bgr=0.0, box=7.5, cache=False, cfg=None, channels_last=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, cls_remap=True, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/content/Dataset_V1_Enhanced/DIATAquarium.v4i.yolov8/enhanced.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dgrad=0.5, dis=6.0, distill_model=None, dlam=1.0, dlog=1.0, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=20, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8n.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=DIATAquarium, nbs=64, nms=None, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=/content/drive/MyDrive/Day17_YOLO_Enhanced, quantize=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/content/drive/MyDrive/Day17_YOLO_Enhanced/DIATAquarium, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=tracktrack.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=11

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 22        [15, 18, 21]  1    753457  ultralytics.nn.modules.head.Detect           [11, 16, None, [64, 128, 256]]
Model summary: 129 layers, 3,012,993 parameters, 3,012,977 gradients, 8.2 GFLOPs

Transferred 319/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.8±0.1 ms, read: 129.4±70.4 MB/s, size: 473.4 KB)
train: Scanning /content/drive/.shortcut-targets-by-id/12c80KPG7UpGhLH4F8MCROtxOtRrpjxRh/Dataset_V1_Enhanced/DIATAquarium.v4i.yolov8/train/labels.cache... 8121 images, 598 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 8121/8121 1.8Git/s 0.0s
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 2.4±1.2 ms, read: 63.6±55.2 MB/s, size: 431.6 KB)
val: Scanning /content/drive/.shortcut-targets-by-id/12c80KPG7UpGhLH4F8MCROtxOtRrpjxRh/Dataset_V1_Enhanced/DIATAquarium.v4i.yolov8/valid/labels.cache... 773 images, 59 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 773/773 57.9Mit/s 0.0s
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.000667, momentum=0.9) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Plotting labels to /content/drive/MyDrive/Day17_YOLO_Enhanced/DIATAquarium/labels.jpg...
Using 8121 train, 773 val images for fraction=1.0 at imgsz=640
Using 2 dataloader workers
Logging results to /content/drive/MyDrive/Day17_YOLO_Enhanced/DIATAquarium
Starting training for 20 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/20      2.43G      1.214      2.083       1.29         49        640: 100% ━━━━━━━━━━━━ 508/508 2.0it/s 4:09
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 25/25 1.5it/s 16.8s
                   all        773       1504      0.776      0.637      0.705      0.431

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/20      2.43G      1.085      1.193      1.182         53        640: 100% ━━━━━━━━━━━━ 508/508 2.0it/s 4:09
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 25/25 1.5it/s 16.4s
                   all        773       1504      0.754      0.751      0.735      0.448

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/20      2.43G      1.061     0.9994      1.163         30        640: 100% ━━━━━━━━━━━━ 508/508 2.0it/s 4:13
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 25/25 1.5it/s 16.9s
                   all        773       1504      0.823      0.792      0.826      0.528

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/20      2.43G      1.031     0.8832      1.149         32        640: 100% ━━━━━━━━━━━━ 508/508 2.0it/s 4:12
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 25/25 1.5it/s 17.0s
                   all        773       1504      0.841      0.787      0.822      0.523

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/20      2.43G      1.002     0.8065      1.133         32        640: 100% ━━━━━━━━━━━━ 508/508 2.0it/s 4:15
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 25/25 1.5it/s 16.3s
                   all        773       1504      0.819      0.825      0.853      0.558

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/20      2.43G     0.9742     0.7505      1.115         41        640: 100% ━━━━━━━━━━━━ 508/508 2.0it/s 4:11
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 25/25 1.5it/s 16.5s
                   all        773       1504      0.828      0.833      0.849      0.561

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/20      2.43G      0.939     0.6966      1.099         43        640: 100% ━━━━━━━━━━━━ 508/508 2.0it/s 4:11
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 25/25 1.5it/s 16.6s
                   all        773       1504       0.85       0.86      0.884      0.574

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/20      2.43G     0.9194     0.6726      1.087         32        640: 100% ━━━━━━━━━━━━ 508/508 2.0it/s 4:14
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 25/25 1.5it/s 16.5s
                   all        773       1504      0.877      0.836      0.876      0.594

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/20      2.43G     0.8964     0.6446      1.078         23        640: 100% ━━━━━━━━━━━━ 508/508 2.0it/s 4:18
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 25/25 1.5it/s 16.9s
                   all        773       1504      0.859      0.863      0.893      0.594

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/20      2.43G     0.8913     0.6139      1.073         62        640: 100% ━━━━━━━━━━━━ 508/508 2.0it/s 4:15
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 25/25 1.6it/s 16.1s
                   all        773       1504       0.87      0.867      0.888      0.604
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/20      2.43G      0.841      0.551      1.055         23        640: 100% ━━━━━━━━━━━━ 508/508 2.1it/s 3:59
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 25/25 1.5it/s 16.5s
                   all        773       1504      0.866      0.862      0.908      0.603

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/20      2.43G     0.8153     0.5172      1.044         16        640: 100% ━━━━━━━━━━━━ 508/508 2.1it/s 3:56
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 25/25 1.5it/s 16.2s
                   all        773       1504      0.853      0.888      0.907      0.605

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/20      2.43G     0.7944     0.4952      1.032         26        640: 100% ━━━━━━━━━━━━ 508/508 2.2it/s 3:53
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 25/25 1.6it/s 16.1s
                   all        773       1504       0.88      0.888      0.914      0.612

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/20      2.43G     0.7785     0.4778      1.023         16        640: 100% ━━━━━━━━━━━━ 508/508 2.2it/s 3:47
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 25/25 1.6it/s 15.9s
                   all        773       1504       0.86      0.897      0.907      0.624

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/20      2.43G      0.761     0.4617      1.011         18        640: 100% ━━━━━━━━━━━━ 508/508 2.2it/s 3:50
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 25/25 1.5it/s 16.5s
                   all        773       1504      0.851      0.896      0.897       0.62

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/20      2.43G     0.7486     0.4501      1.007         15        640: 100% ━━━━━━━━━━━━ 508/508 2.2it/s 3:53
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 25/25 1.6it/s 15.7s
                   all        773       1504      0.878      0.891      0.911      0.624

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/20      2.43G     0.7251     0.4356     0.9941         14        640: 100% ━━━━━━━━━━━━ 508/508 2.2it/s 3:53
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 25/25 1.5it/s 16.8s
                   all        773       1504      0.885      0.884      0.908      0.623

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/20      2.43G      0.712     0.4203     0.9863         16        640: 100% ━━━━━━━━━━━━ 508/508 2.2it/s 3:53
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 25/25 1.6it/s 15.8s
                   all        773       1504      0.868      0.901      0.907      0.628

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/20      2.43G     0.6989     0.4075     0.9805         20        640: 100% ━━━━━━━━━━━━ 508/508 2.2it/s 3:52
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 25/25 1.5it/s 16.4s
                   all        773       1504      0.866       0.91      0.906      0.632

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/20      2.43G     0.6806     0.3944     0.9714         16        640: 100% ━━━━━━━━━━━━ 508/508 2.2it/s 3:52
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 25/25 1.6it/s 15.9s
                   all        773       1504      0.876      0.901      0.911       0.64

20 epochs completed in 1.447 hours.
Optimizer stripped from /content/drive/MyDrive/Day17_YOLO_Enhanced/DIATAquarium/weights/last.pt, 6.2MB
Optimizer stripped from /content/drive/MyDrive/Day17_YOLO_Enhanced/DIATAquarium/weights/best.pt, 6.2MB

Validating /content/drive/MyDrive/Day17_YOLO_Enhanced/DIATAquarium/weights/best.pt...
Ultralytics 8.4.155 🚀 Python-3.13.15 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
Model summary (fused): 72 layers, 3,007,793 parameters, 0 gradients, 8.1 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 25/25 1.5it/s 16.3s
                   all        773       1504      0.877      0.902      0.911       0.64
         Aquatic Plant        358        409      0.973       0.99      0.985      0.789
                Camera         15         15      0.966      0.867      0.952      0.568
           Conch-Shell        143        159      0.916      0.956      0.945      0.703
                  Fish         70        216      0.831      0.821      0.868      0.467
                Fishes         26         26      0.545      0.769      0.651       0.38
                 Pluco         89         90      0.901      0.907      0.923      0.687
                 Shark        187        239      0.924      0.958      0.971      0.652
    Temperature Sensor         32         32      0.812      0.938       0.94      0.661
            Water-Pump        149        151      0.908      0.881       0.94      0.727
          Water-filter         21         21      0.926      0.857      0.889      0.676
                 betta        145        146      0.943      0.979      0.962      0.734
Speed: 0.5ms preprocess, 2.1ms inference, 0.0ms loss, 2.5ms postprocess per image
Results saved to /content/drive/MyDrive/Day17_YOLO_Enhanced/DIATAquarium

In [ ]:
from ultralytics import YOLO
BEST_MODEL="/content/drive/MyDrive/Day17_YOLO_Enhanced/DIATAquarium/weights/best.pt"
DIAT_YAML="/content/Dataset_V1_Enhanced/DIATAquarium.v4i.yolov8/enhanced.yaml"
model=YOLO(BEST_MODEL)
results=model.val(
    data=DIAT_YAML,
    split="val",
    imgsz=640,
    batch=16,
    device=0
)

Ultralytics 8.4.155 🚀 Python-3.13.15 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
Model summary (fused): 72 layers, 3,007,793 parameters, 0 gradients, 8.1 GFLOPs
val: Fast image access ✅ (ping: 0.7±0.1 ms, read: 200.6±34.2 MB/s, size: 466.1 KB)
val: Scanning /content/drive/.shortcut-targets-by-id/12c80KPG7UpGhLH4F8MCROtxOtRrpjxRh/Dataset_V1_Enhanced/DIATAquarium.v4i.yolov8/valid/labels.cache... 773 images, 59 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 773/773 52.3Mit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 49/49 2.7it/s 18.5s
                   all        773       1504      0.876      0.901      0.911      0.639
         Aquatic Plant        358        409      0.973       0.99      0.985       0.79
                Camera         15         15      0.966      0.867      0.952      0.558
           Conch-Shell        143        159      0.916      0.956      0.945        0.7
                  Fish         70        216      0.831      0.819      0.868      0.468
                Fishes         26         26      0.544      0.769      0.655      0.383
                 Pluco         89         90       0.89      0.898      0.919      0.683
                 Shark        187        239      0.925      0.958      0.971      0.651
    Temperature Sensor         32         32      0.813      0.938       0.94      0.661
            Water-Pump        149        151      0.907      0.881       0.94      0.729
          Water-filter         21         21      0.926      0.857      0.889      0.676
                 betta        145        146      0.944      0.979      0.962      0.734
Speed: 1.8ms preprocess, 3.9ms inference, 0.0ms loss, 2.3ms postprocess per image
Results saved to /content/runs/detect/val

In [ ]:
names=model.names
print("DIAT Enhanced — Class-wise Results")
print("-"*75)
for i,name in names.items():
    print(
        f"{name}: "
        f"Precision={results.box.p[i]:.4f}, "
        f"Recall={results.box.r[i]:.4f}, "
        f"mAP50={results.box.ap50[i]:.4f}, "
        f"mAP50-95={results.box.ap[i].mean():.4f}"
    )

DIAT Enhanced — Class-wise Results
---------------------------------------------------------------------------
Aquatic Plant: Precision=0.9732, Recall=0.9902, mAP50=0.9847, mAP50-95=0.7896
Camera: Precision=0.9664, Recall=0.8667, mAP50=0.9523, mAP50-95=0.5577
Conch-Shell: Precision=0.9156, Recall=0.9557, mAP50=0.9453, mAP50-95=0.7005
Fish: Precision=0.8306, Recall=0.8194, mAP50=0.8677, mAP50-95=0.4677
Fishes: Precision=0.5445, Recall=0.7692, mAP50=0.6547, mAP50-95=0.3827
Pluco: Precision=0.8899, Recall=0.8978, mAP50=0.9190, mAP50-95=0.6827
Shark: Precision=0.9245, Recall=0.9582, mAP50=0.9711, mAP50-95=0.6514
Temperature Sensor: Precision=0.8129, Recall=0.9375, mAP50=0.9399, mAP50-95=0.6608
Water-Pump: Precision=0.9073, Recall=0.8808, mAP50=0.9400, mAP50-95=0.7293
Water-filter: Precision=0.9258, Recall=0.8571, mAP50=0.8889, mAP50-95=0.6762
betta: Precision=0.9435, Recall=0.9795, mAP50=0.9623, mAP50-95=0.7338

In [ ]:
import os
import time
VAL_DIR="/content/Dataset_V1_Enhanced/DIATAquarium.v4i.yolov8/valid/images"
images=[
    os.path.join(VAL_DIR,f)
    for f in os.listdir(VAL_DIR)
    if f.lower().endswith((".jpg",".jpeg",".png",".bmp"))
][:100]
start=time.time()
for image in images:
    model.predict(
        source=image,
        imgsz=640,
        device=0,
        verbose=False
    )
total_time=time.time()-start
avg_time=total_time/len(images)
fps=1/avg_time
print("Images measured:",len(images))
print("Total prediction time:",round(total_time,2),"seconds")
print("Average prediction time:",round(avg_time*1000,2),"ms/image")
print("Approximate FPS:",round(fps,2))

Images measured: 100
Total prediction time: 3.0 seconds
Average prediction time: 29.96 ms/image
Approximate FPS: 33.38

In [ ]:
PRED_DIR="/content/drive/MyDrive/Day17_YOLO_Enhanced/DIATAquarium/predictions"

model.predict(
    source=images[:10],
    imgsz=640,
    device=0,
    save=True,
    project=PRED_DIR,
    name="validation_predictions",
    exist_ok=True
)

print("Prediction images saved to:")
print(PRED_DIR)

0: 640x640 1 betta, 6.5ms
1: 640x640 1 Shark, 1 betta, 6.5ms
2: 640x640 1 Aquatic Plant, 1 Shark, 1 Water-Pump, 6.5ms
3: 640x640 1 Shark, 6.5ms
4: 640x640 1 Aquatic Plant, 1 Conch-Shell, 1 Water-Pump, 6.5ms
5: 640x640 1 Conch-Shell, 2 Sharks, 6.5ms
6: 640x640 2 Aquatic Plants, 1 Water-Pump, 6.5ms
7: 640x640 1 Aquatic Plant, 1 Water-Pump, 6.5ms
8: 640x640 1 Water-filter, 1 betta, 6.5ms
9: 640x640 1 Aquatic Plant, 1 Water-Pump, 6.5ms
Speed: 2.8ms preprocess, 6.5ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 640)
Results saved to /content/drive/MyDrive/Day17_YOLO_Enhanced/DIATAquarium/predictions/validation_predictions
Prediction images saved to:
/content/drive/MyDrive/Day17_YOLO_Enhanced/DIATAquarium/predictions

In [ ]:
import os
model_path="/content/drive/MyDrive/Day17_YOLO_Enhanced/DIATAquarium/weights/best.pt"
size_mb=os.path.getsize(model_path)/(1024*1024)
print("Model size:",round(size_mb,2),"MB")
print("Model path:",model_path)

Model size: 5.95 MB
Model path: /content/drive/MyDrive/Day17_YOLO_Enhanced/DIATAquarium/weights/best.pt

In [ ]:
summary="""# DIATAquarium — YOLOv8n Enhanced

## Dataset
- Training images: 8,121
- Validation images: 773
- Test set: Not available in the supplied local dataset
- Number of classes: 11

## Model Configuration
- Model: YOLOv8n
- Epochs: 20
- Image Size: 640 × 640
- Batch Size: 16
- Enhancement: White Balance + CLAHE

## Validation Performance

| Metric | Result |
|---|---:|
| Precision | 87.60% |
| Recall | 90.10% |
| mAP@0.5 | 91.10% |
| mAP@0.5:0.95 | 63.90% |

## Inference Performance
- Images measured: 100
- Total prediction time: 3.00 seconds
- Average prediction time: 29.96 ms/image
- Approximate FPS: 33.38
- Ultralytics inference component: 6.5 ms/image

## Model Information
- Model size: 5.95 MB
- Parameters: 3,007,793
- GFLOPs: 8.1

## Saved Outputs
- Best model: /content/drive/MyDrive/Day17_YOLO_Enhanced/DIATAquarium/weights/best.pt
- Prediction outputs: /content/drive/MyDrive/Day17_YOLO_Enhanced/DIATAquarium/predictions/validation_predictions

## Evaluation Note
The reported Precision, Recall and mAP values were obtained using the 773-image validation set. A separate local test set was not available for DIATAquarium. The enhanced experiment used 20 training epochs, whereas the original Day 16 baseline used 30 epochs. Therefore, the comparison should acknowledge the different training duration.

## Tracking
No video or sequential data was available. Therefore, tracking was not implemented.
"""

path="/content/drive/MyDrive/Day17_YOLO_Enhanced/DIATAquarium/DIATAquarium_Day17_Summary.md"

with open(path,"w") as f:
    f.write(summary)

print("Summary saved successfully!")
print(path)

Summary saved successfully!
/content/drive/MyDrive/Day17_YOLO_Enhanced/DIATAquarium/DIATAquarium_Day17_Summary.md

In [ ]:
import os

BASE="/content/Dataset_V1_Enhanced/Aquatic Plant.v2i.yolov8"

for split in ["train","valid","test"]:
    image_dir=os.path.join(BASE,split,"images")
    label_dir=os.path.join(BASE,split,"labels")

    if not os.path.exists(image_dir):
        print(split,": images folder NOT FOUND")
        continue

    images=[f for f in os.listdir(image_dir) if f.lower().endswith((".jpg",".jpeg",".png",".bmp"))]
    labels=[f for f in os.listdir(label_dir) if f.lower().endswith(".txt")] if os.path.exists(label_dir) else []

    print(split)
    print("Images:",len(images))
    print("Labels:",len(labels))
    print("Missing labels:",len(set(os.path.splitext(f)[0] for f in images)-set(os.path.splitext(f)[0] for f in labels)))
    print()

train
Images: 1892
Labels: 1879
Missing labels: 13

valid : images folder NOT FOUND
test : images folder NOT FOUND

In [ ]:
import os
import cv2
import numpy as np
import shutil
from tqdm import tqdm
ORIGINAL="/content/drive/MyDrive/Dataset_V1"
ENHANCED="/content/Dataset_V1_Enhanced"
def white_balance(img):
    lab=cv2.cvtColor(img,cv2.COLOR_BGR2LAB)
    l,a,b=cv2.split(lab)
    avg_a=np.mean(a)
    avg_b=np.mean(b)
    a=np.clip(a-(avg_a-128)*l/255,0,255).astype(np.uint8)
    b=np.clip(b-(avg_b-128)*l/255,0,255).astype(np.uint8)
    lab=cv2.merge((l,a,b))
    return cv2.cvtColor(lab,cv2.COLOR_LAB2BGR)
def apply_clahe(img):
    lab=cv2.cvtColor(img,cv2.COLOR_BGR2LAB)
    l,a,b=cv2.split(lab)
    clahe=cv2.createCLAHE(clipLimit=2.0,tileGridSize=(8,8))
    l=clahe.apply(l)
    enhanced=cv2.merge((l,a,b))
    return cv2.cvtColor(enhanced,cv2.COLOR_LAB2BGR)
def enhance_image(img):
    return apply_clahe(white_balance(img))
dataset="Aquatic Plant.v2i.yolov8"
for split in ["valid","test"]:
    src_images=os.path.join(ORIGINAL,dataset,split,"images")
    src_labels=os.path.join(ORIGINAL,dataset,split,"labels")
    dst_images=os.path.join(ENHANCED,dataset,split,"images")
    dst_labels=os.path.join(ENHANCED,dataset,split,"labels")
    if not os.path.exists(src_images):
        print(split,"not available in original dataset")
        continue
    os.makedirs(dst_images,exist_ok=True)
    os.makedirs(dst_labels,exist_ok=True)
    image_files=[f for f in os.listdir(src_images) if f.lower().endswith((".jpg",".jpeg",".png",".bmp"))]
    for filename in tqdm(image_files,desc="Enhancing "+split):
        src=os.path.join(src_images,filename)
        dst=os.path.join(dst_images,filename)
        img=cv2.imread(src)
        if img is None:
            continue
        enhanced=enhance_image(img)
        cv2.imwrite(dst,enhanced)
    label_files=[f for f in os.listdir(src_labels) if f.lower().endswith(".txt")]
    for filename in label_files:
        src=os.path.join(src_labels,filename)
        dst=os.path.join(dst_labels,filename)
        shutil.copy2(src,dst)
    print(split,"completed:",len(image_files),"images")

Enhancing valid: 100%|██████████| 179/179 [00:08<00:00, 19.92it/s]

valid completed: 179 images

Enhancing test: 100%|██████████| 89/89 [00:41<00:00,  2.14it/s]

test completed: 89 images

In [ ]:
import os
BASE="/content/Dataset_V1_Enhanced/Aquatic Plant.v2i.yolov8"
for split in ["train","valid","test"]:
    image_dir=os.path.join(BASE,split,"images")
    label_dir=os.path.join(BASE,split,"labels")
    images=[f for f in os.listdir(image_dir) if f.lower().endswith((".jpg",".jpeg",".png",".bmp"))]
    labels=[f for f in os.listdir(label_dir) if f.lower().endswith(".txt")]
    image_names={os.path.splitext(f)[0] for f in images}
    label_names={os.path.splitext(f)[0] for f in labels}
    print(split,": Images =",len(images),"Labels =",len(labels),"Missing labels =",len(image_names-label_names))

train : Images = 1892 Labels = 1879 Missing labels = 13
valid : Images = 179 Labels = 179 Missing labels = 0
test : Images = 89 Labels = 89 Missing labels = 0

In [ ]:
import os
BASE="/content/Dataset_V1_Enhanced/Aquatic Plant.v2i.yolov8"
YAML_PATH=os.path.join(BASE,"enhanced.yaml")
yaml_content="""path: /content/Dataset_V1_Enhanced/Aquatic Plant.v2i.yolov8
train: train/images
val: valid/images
test: test/images
nc: 1
names:
  0: Aquatic_plant
"""
with open(YAML_PATH,"w") as f:
    f.write(yaml_content)
print("YAML created:",YAML_PATH)
print()
print(open(YAML_PATH).read())

YAML created: /content/Dataset_V1_Enhanced/Aquatic Plant.v2i.yolov8/enhanced.yaml

path: /content/Dataset_V1_Enhanced/Aquatic Plant.v2i.yolov8
train: train/images
val: valid/images
test: test/images
nc: 1
names:
  0: Aquatic_plant

In [ ]:
from ultralytics import YOLO
AP_YAML="/content/Dataset_V1_Enhanced/Aquatic Plant.v2i.yolov8/enhanced.yaml"
model=YOLO("yolov8n.pt")
results=model.train(
    data=AP_YAML,
    epochs=30,
    imgsz=640,
    batch=16,
    device=0,
    project="/content/drive/MyDrive/Day17_YOLO_Enhanced",
    name="Aquatic_Plant"
)

Creating new Ultralytics Settings v0.0.8 file ✅
View Ultralytics Settings with 'yolo settings' or at '/root/.config/Ultralytics/settings.json'
Update Settings with 'yolo settings key=value', i.e. 'yolo settings runs_dir=path/to/dir'. For help see https://docs.ultralytics.com/usage/settings.
Downloading https://github.com/ultralytics/assets/releases/download/v8.4.0/yolov8n.pt to 'yolov8n.pt': 100% ━━━━━━━━━━━━ 6.2MB 75.2MB/s 0.1s
Ultralytics 8.4.155 🚀 Python-3.13.15 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=16, bgr=0.0, box=7.5, cache=False, cfg=None, channels_last=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, cls_remap=True, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/content/Dataset_V1_Enhanced/Aquatic Plant.v2i.yolov8/enhanced.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dgrad=0.5, dis=6.0, distill_model=None, dlam=1.0, dlog=1.0, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=30, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8n.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=Aquatic_Plant, nbs=64, nms=None, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=/content/drive/MyDrive/Day17_YOLO_Enhanced, quantize=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/content/drive/MyDrive/Day17_YOLO_Enhanced/Aquatic_Plant, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=tracktrack.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Downloading https://ultralytics.com/assets/Arial.ttf to '/root/.config/Ultralytics/Arial.ttf': 100% ━━━━━━━━━━━━ 755.1KB 23.3MB/s 0.0s
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 22        [15, 18, 21]  1    751507  ultralytics.nn.modules.head.Detect           [1, 16, None, [64, 128, 256]]
Model summary: 129 layers, 3,011,043 parameters, 3,011,027 gradients, 8.2 GFLOPs

Transferred 319/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: downloading yolo26n.pt for AMP checks (one-time, not used for training)...
Downloading https://github.com/ultralytics/assets/releases/download/v8.4.0/yolo26n.pt to 'weights/yolo26n.pt': 100% ━━━━━━━━━━━━ 5.3MB 93.1MB/s 0.1s
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 1328.4±569.1 MB/s, size: 58.0 KB)
train: Scanning /content/Dataset_V1_Enhanced/Aquatic Plant.v2i.yolov8/train/labels... 1879 images, 906 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1892/1892 2.5Kit/s 0.7s
train: New cache created: /content/Dataset_V1_Enhanced/Aquatic Plant.v2i.yolov8/train/labels.cache
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 440.7±187.0 MB/s, size: 51.5 KB)
val: Scanning /content/Dataset_V1_Enhanced/Aquatic Plant.v2i.yolov8/valid/labels... 179 images, 79 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 179/179 1.1Kit/s 0.2s
val: New cache created: /content/Dataset_V1_Enhanced/Aquatic Plant.v2i.yolov8/valid/labels.cache
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.002, momentum=0.9) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Plotting labels to /content/drive/MyDrive/Day17_YOLO_Enhanced/Aquatic_Plant/labels.jpg...
Using 1892 train, 179 val images for fraction=1.0 at imgsz=640
Using 2 dataloader workers
Logging results to /content/drive/MyDrive/Day17_YOLO_Enhanced/Aquatic_Plant
Starting training for 30 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/30      2.03G      1.234      2.515      1.604          6        640: 100% ━━━━━━━━━━━━ 119/119 3.8it/s 30.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 1.4it/s 4.4s
                   all        179        108      0.212      0.185     0.0695     0.0142

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/30      2.59G      1.317      1.877      1.638          2        640: 100% ━━━━━━━━━━━━ 119/119 4.1it/s 29.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 2.5it/s 2.4s
                   all        179        108      0.371      0.222      0.233     0.0724

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/30      2.59G      1.313      1.542      1.624          4        640: 100% ━━━━━━━━━━━━ 119/119 4.1it/s 28.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.4it/s 1.7s
                   all        179        108      0.304      0.343      0.283      0.102

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/30      2.59G      1.333      1.434      1.611          6        640: 100% ━━━━━━━━━━━━ 119/119 4.1it/s 29.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.5it/s 1.7s
                   all        179        108      0.796       0.76      0.864      0.503

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/30      2.59G      1.275      1.315      1.578          5        640: 100% ━━━━━━━━━━━━ 119/119 3.9it/s 30.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.7it/s 1.6s
                   all        179        108      0.664      0.685       0.74      0.404

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/30      2.59G      1.261      1.242      1.565          1        640: 100% ━━━━━━━━━━━━ 119/119 4.1it/s 29.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.2it/s 1.9s
                   all        179        108      0.857       0.87      0.906      0.534

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/30      2.59G      1.211      1.179      1.519          9        640: 100% ━━━━━━━━━━━━ 119/119 4.0it/s 30.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.3it/s 1.8s
                   all        179        108      0.403      0.537       0.42      0.124

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/30      2.59G      1.168      1.075      1.497          6        640: 100% ━━━━━━━━━━━━ 119/119 4.0it/s 29.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.9it/s 1.5s
                   all        179        108      0.898      0.736      0.846      0.538

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/30      2.59G      1.132      1.012      1.462          5        640: 100% ━━━━━━━━━━━━ 119/119 3.9it/s 30.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 4.3it/s 1.4s
                   all        179        108      0.678      0.175      0.261      0.122

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/30      2.59G      1.115      1.014      1.441          2        640: 100% ━━━━━━━━━━━━ 119/119 4.0it/s 29.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.1it/s 1.9s
                   all        179        108      0.783      0.648      0.769      0.447

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/30      2.59G      1.074     0.9894      1.411          7        640: 100% ━━━━━━━━━━━━ 119/119 4.1it/s 29.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 2.9it/s 2.0s
                   all        179        108      0.639      0.685      0.617      0.298

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/30      2.59G      1.095     0.9849      1.426          3        640: 100% ━━━━━━━━━━━━ 119/119 4.2it/s 28.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 2.2it/s 2.7s
                   all        179        108      0.901      0.757       0.89      0.556

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/30      2.59G      1.065     0.9473      1.408          6        640: 100% ━━━━━━━━━━━━ 119/119 4.1it/s 29.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 2.1it/s 2.9s
                   all        179        108      0.929      0.846      0.956      0.583

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/30      2.59G      1.056     0.9736      1.417          7        640: 100% ━━━━━━━━━━━━ 119/119 4.1it/s 28.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 2.5it/s 2.4s
                   all        179        108      0.924        0.9      0.947      0.601

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/30      2.59G      1.017     0.8786      1.372          8        640: 100% ━━━━━━━━━━━━ 119/119 4.0it/s 29.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.8it/s 1.6s
                   all        179        108      0.819      0.843      0.877      0.554

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/30      2.59G      1.025     0.8688       1.38          8        640: 100% ━━━━━━━━━━━━ 119/119 4.1it/s 29.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.6it/s 1.7s
                   all        179        108      0.916      0.906       0.96      0.582

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/30      2.59G      1.011     0.8676      1.372          4        640: 100% ━━━━━━━━━━━━ 119/119 4.0it/s 29.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.9it/s 1.5s
                   all        179        108      0.911      0.898      0.958      0.638

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/30      2.59G      1.018     0.8493      1.365          5        640: 100% ━━━━━━━━━━━━ 119/119 4.0it/s 30.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.6it/s 1.7s
                   all        179        108      0.856      0.898       0.95      0.648

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/30      2.59G     0.9812     0.8085      1.349          7        640: 100% ━━━━━━━━━━━━ 119/119 4.0it/s 29.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.2it/s 1.9s
                   all        179        108      0.904      0.875       0.94      0.648

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/30      2.59G     0.9733     0.8247      1.321          5        640: 100% ━━━━━━━━━━━━ 119/119 4.0it/s 30.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.5it/s 1.7s
                   all        179        108      0.915      0.898      0.963      0.661
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/30      2.59G     0.9557     0.7471      1.449          1        640: 100% ━━━━━━━━━━━━ 119/119 4.1it/s 28.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.7it/s 1.6s
                   all        179        108      0.884       0.92      0.956      0.629

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/30      2.59G     0.8766     0.6628      1.386          1        640: 100% ━━━━━━━━━━━━ 119/119 4.6it/s 25.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 4.0it/s 1.5s
                   all        179        108      0.971      0.924      0.983      0.683

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/30      2.59G     0.8602     0.6355      1.378          2        640: 100% ━━━━━━━━━━━━ 119/119 4.5it/s 26.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.7it/s 1.6s
                   all        179        108      0.934      0.922      0.966      0.639

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/30      2.59G     0.8472     0.6042      1.382          1        640: 100% ━━━━━━━━━━━━ 119/119 4.6it/s 25.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.6it/s 1.7s
                   all        179        108       0.87      0.963      0.969      0.669

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/30      2.59G     0.8087     0.5849      1.331          3        640: 100% ━━━━━━━━━━━━ 119/119 4.5it/s 26.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.8it/s 1.6s
                   all        179        108      0.869      0.919      0.952      0.627

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/30      2.59G     0.7929     0.5484      1.327          2        640: 100% ━━━━━━━━━━━━ 119/119 4.6it/s 26.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.5it/s 1.7s
                   all        179        108      0.934      0.915      0.975      0.673

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/30      2.59G      0.767     0.5232      1.304          2        640: 100% ━━━━━━━━━━━━ 119/119 4.7it/s 25.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 2.4it/s 2.5s
                   all        179        108       0.96       0.89      0.978      0.701

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/30      2.59G     0.7296     0.4941      1.285          3        640: 100% ━━━━━━━━━━━━ 119/119 4.8it/s 24.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 2.5it/s 2.4s
                   all        179        108      0.944      0.941      0.982      0.699

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      29/30      2.59G     0.7384     0.4918      1.263          1        640: 100% ━━━━━━━━━━━━ 119/119 4.8it/s 24.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.4it/s 1.8s
                   all        179        108       0.92      0.963       0.98      0.705

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      30/30      2.59G     0.7021     0.4765      1.265          1        640: 100% ━━━━━━━━━━━━ 119/119 4.6it/s 25.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.8it/s 1.6s
                   all        179        108      0.946       0.98      0.987      0.707

30 epochs completed in 0.259 hours.
Optimizer stripped from /content/drive/MyDrive/Day17_YOLO_Enhanced/Aquatic_Plant/weights/last.pt, 6.2MB
Optimizer stripped from /content/drive/MyDrive/Day17_YOLO_Enhanced/Aquatic_Plant/weights/best.pt, 6.2MB

Validating /content/drive/MyDrive/Day17_YOLO_Enhanced/Aquatic_Plant/weights/best.pt...
Ultralytics 8.4.155 🚀 Python-3.13.15 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
Model summary (fused): 72 layers, 3,005,843 parameters, 0 gradients, 8.1 GFLOPs

In [ ]:
from ultralytics import YOLO
MODEL_PATH="/content/drive/MyDrive/Day17_YOLO_Enhanced/Aquatic_Plant/weights/best.pt"
YAML_PATH="/content/Dataset_V1_Enhanced/Aquatic Plant.v2i.yolov8/enhanced.yaml"
model=YOLO(MODEL_PATH)
test_results=model.val(
    data=YAML_PATH,
    split="test",
    imgsz=640,
    batch=16,
    device=0
)

Ultralytics 8.4.155 🚀 Python-3.13.15 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
Model summary (fused): 72 layers, 3,005,843 parameters, 0 gradients, 8.1 GFLOPs
WARNING ⚠️ val: Slow image access detected (ping: 0.0±0.0 ms, read: 31.8±10.4 MB/s, size: 63.5 KB). Use local storage instead of remote/mounted storage for better performance. See https://docs.ultralytics.com/guides/model-training-tips
val: Scanning /content/Dataset_V1_Enhanced/Aquatic Plant.v2i.yolov8/test/labels... 89 images, 38 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 89/89 329.6it/s 0.3s
val: New cache created: /content/Dataset_V1_Enhanced/Aquatic Plant.v2i.yolov8/test/labels.cache
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 1.7it/s 3.5s
                   all         89         54          1       0.94      0.987      0.719
Speed: 8.3ms preprocess, 9.8ms inference, 0.0ms loss, 2.9ms postprocess per image
Results saved to /content/runs/detect/val

In [ ]:
from ultralytics import YOLO
import os
import time
MODEL_PATH="/content/drive/MyDrive/Day17_YOLO_Enhanced/Aquatic_Plant/weights/best.pt"
IMAGE_DIR="/content/Dataset_V1_Enhanced/Aquatic Plant.v2i.yolov8/valid/images"
model=YOLO(MODEL_PATH)
images=[
    os.path.join(IMAGE_DIR,f)
    for f in os.listdir(IMAGE_DIR)
    if f.lower().endswith((".jpg",".jpeg",".png",".bmp"))
][:100]
start=time.time()
for image in images:
    model.predict(image,imgsz=640,device=0,verbose=False)
total_time=time.time()-start
avg_time=total_time/len(images)
fps=1/avg_time
print("Images measured:",len(images))
print("Total time:",round(total_time,2),"seconds")
print("Average time:",round(avg_time*1000,2),"ms/image")
print("Approximate FPS:",round(fps,2))

Images measured: 100
Total time: 1.39 seconds
Average time: 13.93 ms/image
Approximate FPS: 71.78

In [ ]:
summary="""# Aquatic Plant — Day 17 Enhanced YOLOv8n

## Experiment
- Dataset: Aquatic Plant
- Model: YOLOv8n
- Enhancement: White Balance + CLAHE
- Epochs: 30
- Image Size: 640 × 640
- Batch Size: 16
- Device: Tesla T4 GPU

## Validation Results

| Metric | Result |
|---|---:|
| Precision | 94.6% |
| Recall | 97.9% |
| mAP@0.5 | 98.7% |
| mAP@0.5:0.95 | 70.7% |

## Test Results

| Metric | Result |
|---|---:|
| Precision | 100.0% |
| Recall | 94.0% |
| mAP@0.5 | 98.7% |
| mAP@0.5:0.95 | 71.9% |

## Inference Performance

- Images measured: 100
- Total prediction time: 1.39 seconds
- Average prediction time: 13.93 ms/image
- Approximate FPS: 71.78

## Original vs Enhanced — Test

| Metric | Original | Enhanced |
|---|---:|---:|
| Precision | 95.69% | 100.00% |
| Recall | 94.44% | 94.00% |
| mAP@0.5 | 98.55% | 98.70% |
| mAP@0.5:0.95 | 70.63% | 71.90% |

## Saved Model

/content/drive/MyDrive/Day17_YOLO_Enhanced/Aquatic_Plant/weights/best.pt

## Saved Predictions

/content/drive/MyDrive/Day17_YOLO_Enhanced/Aquatic_Plant/predictions/validation_predictions

## Note

The enhanced model was evaluated on enhanced validation and test images. The comparison with the original model uses the same dataset splits.
"""

path="/content/drive/MyDrive/Day17_YOLO_Enhanced/Aquatic_Plant/Aquatic_Plant_Day17_Summary.md"

with open(path,"w") as f:
    f.write(summary)

print("Aquatic Plant Day 17 summary saved successfully!")
print(path)

Aquatic Plant Day 17 summary saved successfully!
/content/drive/MyDrive/Day17_YOLO_Enhanced/Aquatic_Plant/Aquatic_Plant_Day17_Summary.md

In [ ]:
import os
BASE="/content/Dataset_V1_Enhanced/well.v8i.yolov8"
for split in ["train","valid","test"]:
    images=os.path.join(BASE,split,"images")
    labels=os.path.join(BASE,split,"labels")
    if os.path.exists(images):
        image_count=len([f for f in os.listdir(images) if f.lower().endswith((".jpg",".jpeg",".png",".bmp"))])
        label_count=len([f for f in os.listdir(labels) if f.lower().endswith(".txt")]) if os.path.exists(labels) else 0
        print(split,": Images =",image_count,"Labels =",label_count,"Missing labels =",image_count-label_count)
    else:
        print(split,": NOT FOUND")

train : Images = 3795 Labels = 3780 Missing labels = 15
valid : NOT FOUND
test : NOT FOUND

In [ ]:
import os
import cv2
import numpy as np
import shutil
from tqdm import tqdm
ORIGINAL="/content/drive/MyDrive/Dataset_V1"
ENHANCED="/content/Dataset_V1_Enhanced"
def white_balance(img):
    lab=cv2.cvtColor(img,cv2.COLOR_BGR2LAB)
    l,a,b=cv2.split(lab)
    avg_a=np.mean(a)
    avg_b=np.mean(b)
    a=np.clip(a-(avg_a-128)*l/255,0,255).astype(np.uint8)
    b=np.clip(b-(avg_b-128)*l/255,0,255).astype(np.uint8)
    lab=cv2.merge((l,a,b))
    return cv2.cvtColor(lab,cv2.COLOR_LAB2BGR)
def apply_clahe(img):
    lab=cv2.cvtColor(img,cv2.COLOR_BGR2LAB)
    l,a,b=cv2.split(lab)
    clahe=cv2.createCLAHE(clipLimit=2.0,tileGridSize=(8,8))
    l=clahe.apply(l)
    enhanced=cv2.merge((l,a,b))
    return cv2.cvtColor(enhanced,cv2.COLOR_LAB2BGR)
def enhance_image(img):
    img=white_balance(img)
    img=apply_clahe(img)
    return img
dataset="well.v8i.yolov8"
for split in ["valid","test"]:
    src_images=os.path.join(ORIGINAL,dataset,split,"images")
    src_labels=os.path.join(ORIGINAL,dataset,split,"labels")
    if not os.path.exists(src_images):
        print(split,"not available in original dataset")
        continue
    dst_images=os.path.join(ENHANCED,dataset,split,"images")
    dst_labels=os.path.join(ENHANCED,dataset,split,"labels")
    os.makedirs(dst_images,exist_ok=True)
    os.makedirs(dst_labels,exist_ok=True)
    image_files=[
        f for f in os.listdir(src_images)
        if f.lower().endswith((".jpg",".jpeg",".png",".bmp"))
    ]
    for filename in tqdm(image_files,desc=split):
        src=os.path.join(src_images,filename)
        dst=os.path.join(dst_images,filename)
        img=cv2.imread(src)
        if img is None:
            print("Could not read:",filename)
            continue
        enhanced=enhance_image(img)
        cv2.imwrite(dst,enhanced)
    label_files=[
        f for f in os.listdir(src_labels)
        if f.lower().endswith(".txt")
    ]
    for filename in label_files:
        src=os.path.join(src_labels,filename)
        dst=os.path.join(dst_labels,filename)
        shutil.copy2(src,dst)

    print(split,"completed:",len(image_files),"images")

valid: 100%|██████████| 191/191 [00:07<00:00, 24.36it/s]

valid completed: 191 images

test: 100%|██████████| 184/184 [00:07<00:00, 25.64it/s]

test completed: 184 images

In [ ]:
import os
BASE="/content/Dataset_V1_Enhanced/well.v8i.yolov8"
for split in ["train","valid","test"]:
    images=os.path.join(BASE,split,"images")
    labels=os.path.join(BASE,split,"labels")
    image_count=len([f for f in os.listdir(images) if f.lower().endswith((".jpg",".jpeg",".png",".bmp"))])
    label_count=len([f for f in os.listdir(labels) if f.lower().endswith(".txt")])
    print(split,": Images =",image_count,"Labels =",label_count,"Missing labels =",image_count-label_count)

train : Images = 3795 Labels = 3780 Missing labels = 15
valid : Images = 191 Labels = 191 Missing labels = 0
test : Images = 184 Labels = 184 Missing labels = 0

In [ ]:
import os
import shutil
SOURCE="/content/drive/MyDrive/Dataset_V1_Enhanced/well.v8i.yolov8"
DEST="/content/Dataset_V1_Enhanced/well.v8i.yolov8"
if os.path.exists(DEST):
    print("Local Well enhanced dataset already exists.")
else:
    print("Copying enhanced Well dataset to Colab local storage...")
    shutil.copytree(SOURCE,DEST)
    print("Copy completed successfully!")

print("Local path:",DEST)

Local Well enhanced dataset already exists.
Local path: /content/Dataset_V1_Enhanced/well.v8i.yolov8

In [ ]:
YAML_PATH="/content/Dataset_V1_Enhanced/well.v8i.yolov8/enhanced.yaml"
yaml_content="""path: /content/Dataset_V1_Enhanced/well.v8i.yolov8
train: train/images
val: valid/images
test: test/images
nc: 4
names:
  0: Inlet-pipe
  1: fishes
  2: school-of-fish
  3: stone
"""
with open(YAML_PATH,"w") as f:
    f.write(yaml_content)

print("YAML created successfully!")
print(YAML_PATH)

YAML created successfully!
/content/Dataset_V1_Enhanced/well.v8i.yolov8/enhanced.yaml

In [ ]:
from ultralytics import YOLO
WELL_YAML="/content/Dataset_V1_Enhanced/well.v8i.yolov8/enhanced.yaml"
model=YOLO("yolov8n.pt")
results=model.train(
    data=WELL_YAML,
    epochs=30,
    imgsz=640,
    batch=16,
    device=0,
    project="/content/drive/MyDrive/Day17_YOLO_Enhanced",
    name="Well"
)

Ultralytics 8.4.155 🚀 Python-3.13.15 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=16, bgr=0.0, box=7.5, cache=False, cfg=None, channels_last=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, cls_remap=True, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/content/Dataset_V1_Enhanced/well.v8i.yolov8/enhanced.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dgrad=0.5, dis=6.0, distill_model=None, dlam=1.0, dlog=1.0, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=30, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8n.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=Well, nbs=64, nms=None, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=/content/drive/MyDrive/Day17_YOLO_Enhanced, quantize=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/content/drive/MyDrive/Day17_YOLO_Enhanced/Well, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=tracktrack.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=4

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 22        [15, 18, 21]  1    752092  ultralytics.nn.modules.head.Detect           [4, 16, None, [64, 128, 256]]
Model summary: 129 layers, 3,011,628 parameters, 3,011,612 gradients, 8.2 GFLOPs

Transferred 319/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
WARNING ⚠️ train: Slow image access detected (ping: 0.0±0.0 ms, read: 25.9±11.1 MB/s, size: 55.2 KB). Use local storage instead of remote/mounted storage for better performance. See https://docs.ultralytics.com/guides/model-training-tips
train: Scanning /content/Dataset_V1_Enhanced/well.v8i.yolov8/train/labels... 3780 images, 17 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 3795/3795 548.5it/s 6.9s
train: New cache created: /content/Dataset_V1_Enhanced/well.v8i.yolov8/train/labels.cache
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 468.2±443.4 MB/s, size: 65.2 KB)
val: Scanning /content/Dataset_V1_Enhanced/well.v8i.yolov8/valid/labels... 191 images, 16 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 191/191 1.4Kit/s 0.1s
val: New cache created: /content/Dataset_V1_Enhanced/well.v8i.yolov8/valid/labels.cache
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.00125, momentum=0.9) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Plotting labels to /content/drive/MyDrive/Day17_YOLO_Enhanced/Well/labels.jpg...
Using 3795 train, 191 val images for fraction=1.0 at imgsz=640
Using 2 dataloader workers
Logging results to /content/drive/MyDrive/Day17_YOLO_Enhanced/Well
Starting training for 30 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/30      2.18G      1.788      1.644      1.266         21        640: 100% ━━━━━━━━━━━━ 238/238 3.9it/s 1:02
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 2.5it/s 2.4s
                   all        191       2180      0.591      0.307      0.272      0.108

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/30      2.35G      1.688      1.168      1.242         71        640: 100% ━━━━━━━━━━━━ 238/238 4.1it/s 58.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 2.8it/s 2.1s
                   all        191       2180      0.898      0.247      0.276      0.106

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/30      2.35G      1.675      1.109      1.248         45        640: 100% ━━━━━━━━━━━━ 238/238 4.1it/s 57.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.1it/s 2.0s
                   all        191       2180      0.657      0.318      0.334      0.151

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/30      2.35G      1.642      1.047      1.233         47        640: 100% ━━━━━━━━━━━━ 238/238 4.1it/s 57.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.1it/s 1.9s
                   all        191       2180      0.313      0.356      0.276     0.0933

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/30      2.35G      1.615      1.017      1.224         50        640: 100% ━━━━━━━━━━━━ 238/238 4.1it/s 57.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.0it/s 2.0s
                   all        191       2180      0.614      0.328      0.284      0.114

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/30      2.35G      1.582     0.9827       1.21         19        640: 100% ━━━━━━━━━━━━ 238/238 4.1it/s 57.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 2.5it/s 2.4s
                   all        191       2180      0.577      0.391      0.294      0.114

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/30      2.35G      1.553     0.9544        1.2         67        640: 100% ━━━━━━━━━━━━ 238/238 4.2it/s 56.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.1it/s 2.0s
                   all        191       2180      0.285      0.381      0.309      0.124

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/30      2.35G      1.546     0.9333      1.195         46        640: 100% ━━━━━━━━━━━━ 238/238 4.2it/s 57.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.0it/s 2.0s
                   all        191       2180      0.286      0.373      0.327      0.135

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/30      2.35G      1.519     0.9256      1.191         75        640: 100% ━━━━━━━━━━━━ 238/238 4.2it/s 57.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.0it/s 2.0s
                   all        191       2180      0.596      0.373        0.3      0.116

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/30      2.35G      1.502     0.9027      1.179         26        640: 100% ━━━━━━━━━━━━ 238/238 4.2it/s 57.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.3it/s 1.8s
                   all        191       2180      0.319      0.379      0.317      0.135

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/30      2.35G       1.49       0.89      1.179         17        640: 100% ━━━━━━━━━━━━ 238/238 4.2it/s 56.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 2.6it/s 2.3s
                   all        191       2180      0.671       0.33      0.312      0.121

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/30      2.35G      1.476     0.8862      1.171         84        640: 100% ━━━━━━━━━━━━ 238/238 4.3it/s 55.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 2.0it/s 3.0s
                   all        191       2180       0.64      0.402      0.345      0.138

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/30      2.35G      1.463     0.8675      1.158         49        640: 100% ━━━━━━━━━━━━ 238/238 4.2it/s 56.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 2.0it/s 3.0s
                   all        191       2180      0.369      0.291      0.303      0.126

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/30      2.35G      1.455     0.8625      1.158         77        640: 100% ━━━━━━━━━━━━ 238/238 4.2it/s 56.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 2.2it/s 2.7s
                   all        191       2180      0.337      0.379      0.344      0.148

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/30      2.35G      1.445     0.8522      1.158         84        640: 100% ━━━━━━━━━━━━ 238/238 4.3it/s 54.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 1.9it/s 3.2s
                   all        191       2180      0.693      0.336      0.322      0.139

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/30      2.35G       1.43     0.8385       1.15         65        640: 100% ━━━━━━━━━━━━ 238/238 4.4it/s 54.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 1.9it/s 3.1s
                   all        191       2180      0.656       0.43      0.348      0.147

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/30      2.35G      1.428     0.8343      1.149         50        640: 100% ━━━━━━━━━━━━ 238/238 4.3it/s 55.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 2.0it/s 3.0s
                   all        191       2180      0.713      0.351      0.344      0.144

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/30      2.35G       1.43     0.8348      1.146         69        640: 100% ━━━━━━━━━━━━ 238/238 4.1it/s 58.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 2.1it/s 2.9s
                   all        191       2180       0.63       0.36       0.29      0.127

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/30      2.35G        1.4     0.8243      1.136         56        640: 100% ━━━━━━━━━━━━ 238/238 4.2it/s 57.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 2.5it/s 2.4s
                   all        191       2180      0.608      0.411       0.32      0.135

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/30      2.35G      1.398     0.8085      1.132         80        640: 100% ━━━━━━━━━━━━ 238/238 4.1it/s 57.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 2.4it/s 2.5s
                   all        191       2180      0.293      0.376      0.311      0.134
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/30      2.35G      1.411      0.803      1.163         41        640: 100% ━━━━━━━━━━━━ 238/238 4.5it/s 52.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 1.9it/s 3.1s
                   all        191       2180      0.384       0.34      0.326      0.136

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/30      2.35G      1.389     0.7898      1.154         36        640: 100% ━━━━━━━━━━━━ 238/238 4.6it/s 52.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.3it/s 1.8s
                   all        191       2180      0.331      0.337      0.329      0.143

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/30      2.35G      1.368     0.7825      1.143         38        640: 100% ━━━━━━━━━━━━ 238/238 4.6it/s 51.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 2.9it/s 2.1s
                   all        191       2180      0.324      0.403       0.34      0.147

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/30      2.35G      1.359     0.7752      1.143         47        640: 100% ━━━━━━━━━━━━ 238/238 4.7it/s 50.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.0it/s 2.0s
                   all        191       2180      0.352      0.335      0.322      0.135

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/30      2.35G      1.338     0.7604      1.136         12        640: 100% ━━━━━━━━━━━━ 238/238 4.5it/s 52.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.1it/s 1.9s
                   all        191       2180      0.278      0.426      0.322      0.136

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/30      2.35G      1.333     0.7523      1.128         59        640: 100% ━━━━━━━━━━━━ 238/238 4.7it/s 50.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 2.2it/s 2.7s
                   all        191       2180      0.333      0.367      0.327       0.14

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/30      2.35G      1.317     0.7417      1.125         21        640: 100% ━━━━━━━━━━━━ 238/238 4.7it/s 50.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.2it/s 1.9s
                   all        191       2180      0.332      0.368      0.338      0.147

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/30      2.35G       1.31     0.7381       1.12         15        640: 100% ━━━━━━━━━━━━ 238/238 4.6it/s 51.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 2.0it/s 3.1s
                   all        191       2180      0.356      0.355      0.317      0.134

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      29/30      2.35G      1.295     0.7319      1.116         20        640: 100% ━━━━━━━━━━━━ 238/238 4.7it/s 50.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.0it/s 2.0s
                   all        191       2180      0.352       0.36      0.342      0.149

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      30/30      2.35G      1.286     0.7233      1.111         36        640: 100% ━━━━━━━━━━━━ 238/238 4.5it/s 53.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 2.9it/s 2.1s
                   all        191       2180      0.363      0.377      0.352      0.157

30 epochs completed in 0.484 hours.
Optimizer stripped from /content/drive/MyDrive/Day17_YOLO_Enhanced/Well/weights/last.pt, 6.2MB
Optimizer stripped from /content/drive/MyDrive/Day17_YOLO_Enhanced/Well/weights/best.pt, 6.2MB

Validating /content/drive/MyDrive/Day17_YOLO_Enhanced/Well/weights/best.pt...
Ultralytics 8.4.155 🚀 Python-3.13.15 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
Model summary (fused): 72 layers, 3,006,428 parameters, 0 gradients, 8.1 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 1.1s/it 6.6s
                   all        191       2180      0.363      0.377      0.352      0.157
                fishes        173       2147      0.697      0.679      0.682      0.256
        school-of-fish         24         31      0.393      0.452      0.375      0.214
                 stone          2          2          0          0          0          0
Speed: 3.2ms preprocess, 8.6ms inference, 0.0ms loss, 3.8ms postprocess per image
Results saved to /content/drive/MyDrive/Day17_YOLO_Enhanced/Well

In [ ]:
from ultralytics import YOLO
MODEL_PATH="/content/drive/MyDrive/Day17_YOLO_Enhanced/Well/weights/best.pt"
YAML_PATH="/content/Dataset_V1_Enhanced/well.v8i.yolov8/enhanced.yaml"
model=YOLO(MODEL_PATH)
test_results=model.val(
    data=YAML_PATH,
    split="test",
    imgsz=640,
    batch=16,
    device=0
)

Ultralytics 8.4.155 🚀 Python-3.13.15 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
Model summary (fused): 72 layers, 3,006,428 parameters, 0 gradients, 8.1 GFLOPs
WARNING ⚠️ val: Slow image access detected (ping: 0.0±0.0 ms, read: 19.0±14.4 MB/s, size: 67.7 KB). Use local storage instead of remote/mounted storage for better performance. See https://docs.ultralytics.com/guides/model-training-tips
val: Scanning /content/Dataset_V1_Enhanced/well.v8i.yolov8/test/labels... 184 images, 21 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 184/184 331.8it/s 0.6s
val: New cache created: /content/Dataset_V1_Enhanced/well.v8i.yolov8/test/labels.cache
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 2.8it/s 4.2s
                   all        184       2111      0.431      0.394      0.411      0.181
                fishes        161       2065      0.707       0.67      0.692       0.26
        school-of-fish         23         43      0.586      0.512      0.541      0.282
                 stone          3          3          0          0          0          0
Speed: 3.3ms preprocess, 4.7ms inference, 0.0ms loss, 1.8ms postprocess per image
Results saved to /content/runs/detect/val-2

In [ ]:
from ultralytics import YOLO
import os
import time
MODEL_PATH="/content/drive/MyDrive/Day17_YOLO_Enhanced/Well/weights/best.pt"
IMAGE_DIR="/content/Dataset_V1_Enhanced/well.v8i.yolov8/valid/images"
model=YOLO(MODEL_PATH)
image_files=[
    os.path.join(IMAGE_DIR,f)
    for f in os.listdir(IMAGE_DIR)
    if f.lower().endswith((".jpg",".jpeg",".png",".bmp"))
][:100]
start=time.time()
for image_path in image_files:
    model.predict(
        source=image_path,
        imgsz=640,
        device=0,
        verbose=False
    )
total_time=time.time()-start
avg_time=total_time/len(image_files)
fps=1/avg_time
print("Images measured:",len(image_files))
print("Total prediction time:",round(total_time,2),"seconds")
print("Average prediction time:",round(avg_time*1000,2),"ms/image")
print("Approximate FPS:",round(fps,2))

Images measured: 100
Total prediction time: 1.58 seconds
Average prediction time: 15.82 ms/image
Approximate FPS: 63.23

In [ ]:
from IPython.display import display
import pandas as pd
import os

save_dir="/content/drive/MyDrive/Day17_YOLO_Enhanced/Well"
os.makedirs(save_dir,exist_ok=True)

validation_data={
    "Metric":["Precision","Recall","mAP@0.5","mAP@0.5:0.95"],
    "Original":[35.6,36.8,36.5,16.4],
    "Enhanced":[36.3,37.7,35.2,15.7]
}

validation_df=pd.DataFrame(validation_data)
validation_df["Change (pp)"]=validation_df["Enhanced"]-validation_df["Original"]

print("WELL — VALIDATION RESULTS")
display(validation_df)

test_df=pd.DataFrame({
    "Metric":["Precision","Recall","mAP@0.5","mAP@0.5:0.95"],
    "Enhanced Test":[43.1,39.4,41.1,18.1]
})

print("WELL — TEST RESULTS")
display(test_df)

class_df=pd.DataFrame({
    "Class":["Inlet-pipe","fishes","school-of-fish","stone"],
    "Precision":["—",70.7,58.6,0.0],
    "Recall":["—",67.0,51.2,0.0],
    "mAP@0.5":["—",69.2,54.1,0.0],
    "mAP@0.5:0.95":["—",26.0,28.2,0.0]
})

print("WELL — TEST CLASS-WISE RESULTS")
display(class_df)

summary=f"""# Well — YOLOv8n Enhanced Detection — Day 17

## Dataset
- Training images: 3,795
- Validation images: 191
- Test images: 184
- Number of classes: 4
- Classes: Inlet-pipe,fishes,school-of-fish,stone

## Model Configuration
- Model: YOLOv8n
- Epochs: 30
- Image Size: 640 × 640
- Batch Size: 16
- Device: Tesla T4 GPU
- Enhancement: White Balance + CLAHE

## Validation Performance

| Metric | Original | Enhanced | Change |
|---|---:|---:|---:|
| Precision | 35.6% | 36.3% | +0.7 pp |
| Recall | 36.8% | 37.7% | +0.9 pp |
| mAP@0.5 | 36.5% | 35.2% | -1.3 pp |
| mAP@0.5:0.95 | 16.4% | 15.7% | -0.7 pp |

## Enhanced Test Set Performance

- Test images: 184
- Test instances: 2,111

| Metric | Enhanced Test |
|---|---:|
| Precision | 43.1% |
| Recall | 39.4% |
| mAP@0.5 | 41.1% |
| mAP@0.5:0.95 | 18.1% |

## Test Class-wise Evaluation

| Class | Precision | Recall | mAP@0.5 | mAP@0.5:0.95 |
|---|---:|---:|---:|---:|
| Inlet-pipe | — | — | — | — |
| fishes | 70.7% | 67.0% | 69.2% | 26.0% |
| school-of-fish | 58.6% | 51.2% | 54.1% | 28.2% |
| stone | 0.0% | 0.0% | 0.0% | 0.0% |

## Inference Performance

- Images measured: 100
- Total prediction time: 1.58 seconds
- Average prediction time: 15.82 ms/image
- Approximate FPS: 63.23

## Model Information

- Parameters: 3,006,428
- GFLOPs: 8.1
- Best model:
  `/content/drive/MyDrive/Day17_YOLO_Enhanced/Well/weights/best.pt`

## Prediction Outputs

- Validation prediction outputs:
  `/content/drive/MyDrive/Day17_YOLO_Enhanced/Well/predictions/validation_predictions`

## Findings

- The Well dataset shows substantially lower detection performance than the other two datasets.
- The original and enhanced validation results are similar.
- White Balance + CLAHE slightly increased Precision and Recall,but mAP@0.5 and mAP@0.5:0.95 decreased slightly.
- The test set contains strong class imbalance,with 2,065 of 2,111 instances belonging to the fishes class.
- The stone class has only 3 test instances and was not detected.
- Inlet-pipe does not have a reported test metric in the evaluation output.

## Tracking

No video or sequential data is currently available. Therefore,tracking was not implemented.

## Conclusion

For the Well dataset,White Balance + CLAHE did not produce an overall improvement in YOLOv8n detection performance compared with the original-image baseline. The experiment demonstrates that the effect of underwater image enhancement is dataset-dependent.
"""

summary_path=os.path.join(save_dir,"Well_Day17_Summary.md")

with open(summary_path,"w") as f:
    f.write(summary)

print("Summary saved to:")
print(summary_path)

WELL — VALIDATION RESULTS

         Metric  Original  Enhanced  Change (pp)
0     Precision      35.6      36.3          0.7
1        Recall      36.8      37.7          0.9
2       mAP@0.5      36.5      35.2         -1.3
3  mAP@0.5:0.95      16.4      15.7         -0.7

WELL — TEST RESULTS

         Metric  Enhanced Test
0     Precision           43.1
1        Recall           39.4
2       mAP@0.5           41.1
3  mAP@0.5:0.95           18.1

WELL — TEST CLASS-WISE RESULTS

            Class Precision Recall mAP@0.5 mAP@0.5:0.95
0      Inlet-pipe         —      —       —            —
1          fishes      70.7   67.0    69.2         26.0
2  school-of-fish      58.6   51.2    54.1         28.2
3           stone       0.0    0.0     0.0          0.0

Summary saved to:
/content/drive/MyDrive/Day17_YOLO_Enhanced/Well/Well_Day17_Summary.md

In [ ]:
import pandas as pd
comparison_data=[
    ["DIATAquarium","Original",90.02,92.09,92.72,65.90],
    ["DIATAquarium","Enhanced",87.70,90.20,91.10,64.00],
    ["Aquatic Plant","Original",94.64,93.52,98.05,70.79],
    ["Aquatic Plant","Enhanced",94.60,97.90,98.70,70.70],
    ["Well","Original",35.60,36.80,36.50,16.40],
    ["Well","Enhanced",36.30,37.70,35.20,15.70]
]
df=pd.DataFrame(
    comparison_data,
    columns=[
        "Dataset",
        "Version",
        "Precision (%)",
        "Recall (%)",
        "mAP@0.5 (%)",
        "mAP@0.5:0.95 (%)"
    ]
)
display(df)

,Dataset,Version,Precision (%),Recall (%),mAP@0.5 (%),mAP@0.5:0.95 (%)
0,DIATAquarium,Original,90.02,92.09,92.72,65.90
1,DIATAquarium,Enhanced,87.70,90.20,91.10,64.00
2,Aquatic Plant,Original,94.64,93.52,98.05,70.79
3,Aquatic Plant,Enhanced,94.60,97.90,98.70,70.70
4,Well,Original,35.60,36.80,36.50,16.40
5,Well,Enhanced,36.30,37.70,35.20,15.70

In [ ]:
original=df[df["Version"]=="Original"].set_index("Dataset")
enhanced=df[df["Version"]=="Enhanced"].set_index("Dataset")
change=pd.DataFrame({
    "Precision Change (pp)":enhanced["Precision (%)"]-original["Precision (%)"],
    "Recall Change (pp)":enhanced["Recall (%)"]-original["Recall (%)"],
    "mAP@0.5 Change (pp)":enhanced["mAP@0.5 (%)"]-original["mAP@0.5 (%)"],
    "mAP@0.5:0.95 Change (pp)":enhanced["mAP@0.5:0.95 (%)"]-original["mAP@0.5:0.95 (%)"]
})
display(change.round(2))

,Precision Change (pp),Recall Change (pp),mAP@0.5 Change (pp),mAP@0.5:0.95 Change (pp)
Dataset,,,,
DIATAquarium,-2.32,-1.89,-1.62,-1.90
Aquatic Plant,-0.04,4.38,0.65,-0.09
Well,0.70,0.90,-1.30,-0.70

In [ ]:
save_path="/content/drive/MyDrive/Day17_YOLO_Enhanced/Day17_Original_vs_Enhanced_Comparison.csv"
df.to_csv(save_path,index=False)
print("Comparison table saved:")
print(save_path)

Comparison table saved:
/content/drive/MyDrive/Day17_YOLO_Enhanced/Day17_Original_vs_Enhanced_Comparison.csv

In [ ]:
import pandas as pd
speed_data=[
    ["DIATAquarium","Original",21.25,47.05],
    ["DIATAquarium","Enhanced",29.96,33.38],
    ["Aquatic Plant","Original",12.60,79.35],
    ["Aquatic Plant","Enhanced",13.93,71.78],
    ["Well","Original",18.55,53.91],
    ["Well","Enhanced",15.82,63.23]
]
speed_df=pd.DataFrame(
    speed_data,
    columns=["Dataset","Version","Average Time (ms/image)","FPS"]
)
display(speed_df)

         Dataset   Version  Average Time (ms/image)    FPS
0   DIATAquarium  Original                    21.25  47.05
1   DIATAquarium  Enhanced                    29.96  33.38
2  Aquatic Plant  Original                    12.60  79.35
3  Aquatic Plant  Enhanced                    13.93  71.78
4           Well  Original                    18.55  53.91
5           Well  Enhanced                    15.82  63.23

In [ ]:
original=speed_df[speed_df["Version"]=="Original"].set_index("Dataset")
enhanced=speed_df[speed_df["Version"]=="Enhanced"].set_index("Dataset")
speed_change=pd.DataFrame({
    "Inference Time Change (ms)":enhanced["Average Time (ms/image)"]-original["Average Time (ms/image)"],
    "FPS Change":enhanced["FPS"]-original["FPS"]
})
display(speed_change.round(2))

               Inference Time Change (ms)  FPS Change
Dataset
DIATAquarium                         8.71      -13.67
Aquatic Plant                        1.33       -7.57
Well                                -2.73        9.32

In [ ]:
save_path="/content/drive/MyDrive/Day17_YOLO_Enhanced/Day17_Inference_Speed_Comparison.csv"
speed_df.to_csv(save_path,index=False)
print("Saved:")
print(save_path)

Saved:
/content/drive/MyDrive/Day17_YOLO_Enhanced/Day17_Inference_Speed_Comparison.csv

# Day 17 — Final Findings and Conclusion

## Overall Findings

- White Balance + CLAHE was evaluated with YOLOv8n across all three supplied underwater datasets.
- The effect of image enhancement was dataset-dependent.
- DIATAquarium showed a decrease in the reported detection metrics after enhancement.
- Aquatic Plant showed an improvement in Recall and mAP@0.5,while the other metrics changed only slightly.
- Well showed small improvements in Precision and Recall,but mAP@0.5 and mAP@0.5:0.95 decreased slightly.
- Inference speed also changed differently across datasets.
- No video or sequential data was available,so object tracking was not implemented.

## Configuration Limitation

- The original and enhanced experiments used the same YOLOv8n architecture,640 × 640 image size and batch size of 16.
- DIATAquarium original training used 30 epochs,while the enhanced experiment used 20 epochs. This difference is documented as a comparability limitation.

## Conclusion

The Day 17 experiment shows that White Balance + CLAHE does not consistently improve YOLOv8n object detection across all underwater datasets. Its effect depends on the characteristics of the dataset. The original and enhanced detection results,inference performance,and class-wise behaviour were recorded for further analysis.

## Tracking Status

No video or sequential data was available. Therefore,tracking was not implemented in the current project scope.